import type { INodeProperties } from 'n8n-workflow';

export const botOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['bot'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a bot',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a bot',
			},
			{
				name: 'Get Many Events',
				value: 'getAllEvents',
				action: 'Get many bot events',
			},
			{
				name: 'Remove Events',
				value: 'removeEvents',
				action: 'Remove events from bot',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a bot',
			},
			{
				name: 'Update Webhook',
				value: 'updateWebhook',
				action: 'Update bot webhook',
			},
		],
		default: 'updateWebhook',
	},
];

export const botFields: INodeProperties[] = [
	{
		displayName: 'Requires bot roles',
		name: 'botUpdateWebhookNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['bot'], operation: ['updateWebhook'] } },
	},
	{
		displayName: 'Outgoing URL',
		name: 'outgoingUrl',
		type: 'string',
		required: true,
		default: "",
		description: 'Outgoing webhook URL. An empty string disables the webhook.',
		displayOptions: { show: { resource: ['bot'], operation: ['updateWebhook'] } },
		placeholder: 'https://www.website.com/tasks/new',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'botCreateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['bot'], operation: ['create'] } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: "",
		description: 'Bot name',
		displayOptions: { show: { resource: ['bot'], operation: ['create'] } },
		placeholder: 'Tasks bot',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['bot'], operation: ['create'] } },
		options: [
			{
				displayName: 'Commands',
				name: 'commands',
				type: 'string',
				default: "",
				description: 'Bot commands (trigger words) it reacts to when trigger_on = commands',
				placeholder: '/task,/help',
			},
			{
				displayName: 'Events',
				name: 'events',
				type: 'string',
				default: "",
				description: 'Events the bot is subscribed to',
				placeholder: 'message_new',
			},
			{
				displayName: 'Nickname',
				name: 'nickname',
				type: 'string',
				default: "",
				description: 'Bot nickname. Must end with `_bot`.',
				placeholder: 'tasks_bot',
			},
			{
				displayName: 'Outgoing URL',
				name: 'outgoingUrl',
				type: 'string',
				default: "",
				description: 'Outgoing webhook URL',
				placeholder: 'https://www.website.com/tasks/new',
			},
			{
				displayName: 'Scopes',
				name: 'scopes',
				type: 'string',
				default: "",
				description: 'Bot token scopes (permissions). If omitted, the bot receives the default set.',
				placeholder: 'messages:create',
			},
			{
				displayName: 'Trigger On',
				name: 'triggerOn',
				type: 'options',
				options: [{ name: 'All Messages', value: 'all_messages', description: 'On all messages in chats where the bot is present' },
{ name: 'Commands', value: 'commands', description: 'Only on commands (trigger words) from commands' },
{ name: 'Unfurl', value: 'unfurl', description: 'On link unfurling (link previews)' }],
				default: "commands",
				description: 'Outgoing webhook trigger condition',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['bot'], operation: ['get'] } },
		description: 'Bot ID',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'botGetNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['bot'], operation: ['get'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['bot'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'botId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['bot'], operation: ['update'] } },
		description: 'Bot ID',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'botUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['bot'], operation: ['update'] } },
	},
	{
		displayName: 'Webhook URL',
		name: 'webhookUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/webhook',
		description: 'URL for the outgoing webhook',
		displayOptions: { show: { resource: ['bot'], operation: ['update'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['bot'], operation: ['update'] } },
		options: [
			{
				displayName: 'Commands',
				name: 'commands',
				type: 'string',
				default: "",
				description: 'Bot commands (trigger words) it reacts to when trigger_on = commands',
				placeholder: '/task,/help',
			},
			{
				displayName: 'Events',
				name: 'events',
				type: 'string',
				default: "",
				description: 'Events the bot is subscribed to',
				placeholder: 'message_new',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: "",
				description: 'Bot name',
				placeholder: 'Tasks bot',
			},
			{
				displayName: 'Nickname',
				name: 'nickname',
				type: 'string',
				default: "",
				description: 'Bot nickname. Must end with `_bot`.',
				placeholder: 'tasks_bot',
			},
			{
				displayName: 'Outgoing URL',
				name: 'webhookUrl',
				type: 'string',
				default: "",
				description: 'Outgoing webhook URL',
				placeholder: 'https://www.website.com/tasks/new',
			},
			{
				displayName: 'Scopes',
				name: 'scopes',
				type: 'string',
				default: "",
				description: 'Bot token scopes (permissions). If omitted, the bot receives the default set.',
				placeholder: 'messages:create',
			},
			{
				displayName: 'Trigger On',
				name: 'triggerOn',
				type: 'options',
				options: [{ name: 'All Messages', value: 'all_messages', description: 'On all messages in chats where the bot is present' },
{ name: 'Commands', value: 'commands', description: 'Only on commands (trigger words) from commands' },
{ name: 'Unfurl', value: 'unfurl', description: 'On link unfurling (link previews)' }],
				default: "commands",
				description: 'Outgoing webhook trigger condition',
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['bot'], operation: ['getAllEvents'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['bot'], operation: ['getAllEvents'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['bot'], operation: ['getAllEvents'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['bot'], operation: ['removeEvents'] } },
		description: 'Event ID',
	},
];