import type { INodeProperties } from 'n8n-workflow';

export const chatOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['chat'] } },
		options: [
			{
				name: 'Archive',
				value: 'archive',
				action: 'Archive a chat',
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a chat',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a chat',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many chats',
			},
			{
				name: 'Unarchive',
				value: 'unarchive',
				action: 'Unarchive a chat',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a chat',
			},
		],
		default: 'getAll',
	},
];

export const chatFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'chatName',
		type: 'string',
		required: true,
		default: "",
		displayOptions: { show: { resource: ['chat'], operation: ['create'] } },
		placeholder: '🤿 aqua',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['chat'], operation: ['create'] } },
		options: [
			{
				displayName: 'Channel',
				name: 'channel',
				type: 'boolean',
				default: false,
				description: 'Whether this is a channel',
				routing: { send: { type: 'body', property: 'channel' } },
			},
			{
				displayName: 'Group Tag IDs',
				name: 'groupTagIds',
				type: 'string',
				default: "",
				description: 'Array of tag IDs to be added as members',
				placeholder: '86,18',
			},
			{
				displayName: 'Member IDs',
				name: 'memberIds',
				type: 'string',
				default: "",
				description: 'Array of user IDs who will become members',
				placeholder: '186,187',
			},
			{
				displayName: 'Public',
				name: 'public',
				type: 'boolean',
				default: false,
				description: 'Whether to publicly accessible',
				routing: { send: { type: 'body', property: 'public' } },
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'options',
		options: [{ name: 'ID', value: 'id', description: 'By chat ID' },
{ name: 'Last Message At', value: 'last_message_at', description: 'By last message date and time' }],
		default: "id",
		description: 'Sort field',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'sort' } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'options',
		options: [{ name: 'Asc', value: 'asc', description: 'Ascending' },
{ name: 'Desc', value: 'desc', description: 'Descending' }],
		default: "desc",
		description: 'Sort direction',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'order' } },
	},
	{
		displayName: 'Availability',
		name: 'availability',
		type: 'options',
		options: [{ name: 'Is Member', value: 'is_member', description: 'Chats where the user is a member' },
{ name: 'Public', value: 'public', description: 'All public chats in the workspace, regardless of user membership' }],
		default: "is_member",
		description: 'Parameter that controls chat availability and filtering for the user',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'availability' } },
	},
	{
		displayName: 'Last Message At After',
		name: 'lastMessageAtAfter',
		type: 'dateTime',
		default: "",
		description: 'Filter by last message creation time. Returns chats where the last message was created no earlier than the specified time (in YYYY-MM-DDThh:mm:ss.sssZ format).',
		placeholder: '2025-01-01T00:00:00.000Z',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'last_message_at_after' } },
	},
	{
		displayName: 'Last Message At Before',
		name: 'lastMessageAtBefore',
		type: 'dateTime',
		default: "",
		description: 'Filter by last message creation time. Returns chats where the last message was created no later than the specified time (in YYYY-MM-DDThh:mm:ss.sssZ format).',
		placeholder: '2025-02-01T00:00:00.000Z',
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'last_message_at_before' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['chat'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Personal',
				name: 'personal',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by direct and group chats. If not specified, all chats are returned.',
				routing: { send: { type: 'query', property: 'personal' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['chat'], operation: ['get'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['chat'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['chat'], operation: ['update'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['chat'], operation: ['update'] } },
		options: [
			{
				displayName: 'Name',
				name: 'chatName',
				type: 'string',
				default: "",
				placeholder: 'Pool',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Public',
				name: 'public',
				type: 'boolean',
				default: false,
				description: 'Whether to publicly accessible',
				routing: { send: { type: 'body', property: 'public' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['chat'], operation: ['archive'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['chat'], operation: ['unarchive'] } },
	},
];