import type { INodeProperties } from 'n8n-workflow';

export const draftOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['draft'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a draft',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a draft',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a draft',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many drafts',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a draft',
			},
		],
		default: 'create',
	},
];

export const draftFields: INodeProperties[] = [
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'draftCreateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['draft'], operation: ['create'] } },
	},
	{
		displayName: 'Entity Type',
		name: 'entityType',
		type: 'options',
		required: true,
		options: [{ name: 'Discussion', value: 'discussion', description: 'Conversation or channel' },
{ name: 'Thread', value: 'thread' },
{ name: 'User', value: 'user' }],
		default: "discussion",
		description: 'Where the draft is written: to a conversation or a channel, to a thread, or to a direct message with an employee',
		displayOptions: { show: { resource: ['draft'], operation: ['create'] } },
	},
	{
		displayName: 'Entity ID',
		name: 'entityId',
		type: 'number',
		required: true,
		default: 0,
		description: 'ID of what is named in `entity_type`: the conversation or channel, the thread, or the employee',
		displayOptions: { show: { resource: ['draft'], operation: ['create'] } },
		placeholder: '334',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['draft'], operation: ['create'] } },
		options: [
			{
				displayName: 'Content',
				name: 'content',
				type: 'string',
				typeOptions: { rows: 4 },
				default: "",
				description: 'Draft text. It may be omitted if there are attachments, but a draft cannot be empty.',
				placeholder: 'Weekly report: sales are up 10%',
			},
			{
				displayName: 'Files',
				name: 'files',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'file',
					displayName: 'File',
					values: [
						{
							displayName: 'Duration Ms',
							name: 'duration_ms',
							type: 'number',
							default: 0,
							description: 'Duration in milliseconds. Required for a voice message (`file_type` is `voice`).',
						},
						{
							displayName: 'File Type',
							name: 'file_type',
							type: 'options',
							options: [{ name: 'Audio', value: 'audio', description: 'Audio file' },
{ name: 'File', value: 'file', description: 'Regular file' },
{ name: 'Image', value: 'image' },
{ name: 'Video', value: 'video', description: 'Video file' },
{ name: 'Voice', value: 'voice', description: 'Voice message' }],
							default: "",
						},
						{
							displayName: 'Height',
							name: 'height',
							type: 'number',
							default: 0,
							description: 'Image height in pixels',
						},
						{
							displayName: 'ID',
							name: 'id',
							type: 'number',
							default: 0,
							description: 'ID of a file that is already attached. It is passed when editing, to keep the attachment as it is. For a new file it is not specified.',
						},
						{
							displayName: 'Key',
							name: 'key',
							type: 'string',
							default: "",
							description: 'File path obtained from the [Upload file](POST /direct_url) method',
						},
						{
							displayName: 'Name',
							name: 'name',
							type: 'string',
							default: "",
							description: 'File name to display to the user',
						},
						{
							displayName: 'Size',
							name: 'size',
							type: 'number',
							default: 0,
							description: 'File size in bytes, displayed to the user',
						},
						{
							displayName: 'Waveform',
							name: 'waveform',
							type: 'string',
							default: "",
							description: 'Waveform for visualization. Required for a voice message (`file_type` is `voice`).',
						},
						{
							displayName: 'Width',
							name: 'width',
							type: 'number',
							default: 0,
							description: 'Image width in pixels',
						},
					],
				}],
				default: [],
				description: 'Files to attach, no more than ten',
			},
			{
				displayName: 'Parent Message ID',
				name: 'parentMessageId',
				type: 'number',
				default: 0,
				description: 'ID of the message the draft will be sent as a reply to. The message must be in the same chat.',
				placeholder: '196093',
			},
			{
				displayName: 'Schedule',
				name: 'schedule',
				type: 'json',
				default: "{}",
				description: 'Sending schedule. With it a scheduled message is created, without it an ordinary draft.',
			},
		],
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'draftGetAllNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		options: [{ name: 'All', value: 'all', description: 'Both drafts and scheduled messages' },
{ name: 'Regular', value: 'regular', description: 'Ordinary drafts' },
{ name: 'Scheduled', value: 'scheduled', description: 'Scheduled messages' }],
		default: "regular",
		description: 'What to return: `regular` — ordinary drafts, `scheduled` — scheduled messages, `all` — both',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'Entity Type',
		name: 'entityType',
		type: 'options',
		options: [{ name: 'Discussion', value: 'discussion', description: 'Conversation or channel' },
{ name: 'Thread', value: 'thread' },
{ name: 'User', value: 'user' }],
		default: "",
		description: 'Chat type for filtering by a single chat. Specified together with `entity_id`: sending only one of the two returns `422`.',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'Entity ID',
		name: 'entityId',
		type: 'number',
		default: 0,
		description: 'ID of what is named in `entity_type`. Specified together with it.',
		placeholder: '334',
		displayOptions: { show: { resource: ['draft'], operation: ['getAll'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['draft'], operation: ['get'] } },
		description: 'Draft ID',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'draftGetNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['draft'], operation: ['get'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['draft'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['draft'], operation: ['update'] } },
		description: 'Draft ID',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'draftUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['draft'], operation: ['update'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['draft'], operation: ['update'] } },
		options: [
			{
				displayName: 'Content',
				name: 'content',
				type: 'string',
				typeOptions: { rows: 4 },
				default: "",
				description: 'Draft text',
				placeholder: 'Weekly report: sales are up 10%',
			},
			{
				displayName: 'Files',
				name: 'files',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'file',
					displayName: 'File',
					values: [
						{
							displayName: 'Duration Ms',
							name: 'duration_ms',
							type: 'number',
							default: 0,
							description: 'Duration in milliseconds. Required for a voice message (`file_type` is `voice`).',
						},
						{
							displayName: 'File Type',
							name: 'file_type',
							type: 'options',
							options: [{ name: 'Audio', value: 'audio', description: 'Audio file' },
{ name: 'File', value: 'file', description: 'Regular file' },
{ name: 'Image', value: 'image' },
{ name: 'Video', value: 'video', description: 'Video file' },
{ name: 'Voice', value: 'voice', description: 'Voice message' }],
							default: "",
						},
						{
							displayName: 'Height',
							name: 'height',
							type: 'number',
							default: 0,
							description: 'Image height in pixels',
						},
						{
							displayName: 'ID',
							name: 'id',
							type: 'number',
							default: 0,
							description: 'ID of a file that is already attached. It is passed when editing, to keep the attachment as it is. For a new file it is not specified.',
						},
						{
							displayName: 'Key',
							name: 'key',
							type: 'string',
							default: "",
							description: 'File path obtained from the [Upload file](POST /direct_url) method',
						},
						{
							displayName: 'Name',
							name: 'name',
							type: 'string',
							default: "",
							description: 'File name to display to the user',
						},
						{
							displayName: 'Size',
							name: 'size',
							type: 'number',
							default: 0,
							description: 'File size in bytes, displayed to the user',
						},
						{
							displayName: 'Waveform',
							name: 'waveform',
							type: 'string',
							default: "",
							description: 'Waveform for visualization. Required for a voice message (`file_type` is `voice`).',
						},
						{
							displayName: 'Width',
							name: 'width',
							type: 'number',
							default: 0,
							description: 'Image width in pixels',
						},
					],
				}],
				default: [],
				description: 'Files to attach, no more than ten. The array you pass replaces the previous set: an empty one removes all the attachments, and to keep a file that is already attached, pass it with its `ID`. Without this field the attachments stay as they were.',
			},
			{
				displayName: 'Parent Message ID',
				name: 'parentMessageId',
				type: 'number',
				default: 0,
				description: 'ID of the message the draft will be sent as a reply to. `null` removes the reply.',
				placeholder: '196093',
			},
			{
				displayName: 'Schedule',
				name: 'schedule',
				type: 'json',
				default: "{}",
				description: 'Sending schedule. For an ordinary draft it turns the draft into a scheduled message. For a scheduled message the schedule can be changed but not removed: `null` gives `422` with the `draft_type_change_forbidden` code in response.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['draft'], operation: ['delete'] } },
		description: 'Draft ID',
	},
	{
		displayName: 'Requires owner, admin, user roles',
		name: 'draftDeleteNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['draft'], operation: ['delete'] } },
	},
];