import type { INodeProperties } from 'n8n-workflow';

export const formOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['form'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a form',
			},
		],
		default: 'create',
	},
];

export const formFields: INodeProperties[] = [
	{
		displayName: 'Title',
		name: 'formTitle',
		type: 'string',
		required: true,
		default: "",
		description: 'View title',
		displayOptions: { show: { resource: ['form'], operation: ['create'] } },
		placeholder: 'Vacation notification',
		routing: { send: { type: 'body', property: 'title' } },
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		required: true,
		options: [{ name: 'Modal', value: 'modal', description: 'Modal window' }],
		default: "modal",
		description: 'View opening method',
		displayOptions: { show: { resource: ['form'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'type' } },
	},
	{
		displayName: 'Trigger ID',
		name: 'triggerId',
		type: 'string',
		required: true,
		default: "",
		description: 'Unique event identifier (received, for example, in the outgoing webhook for a button click)',
		hint: 'Trigger ID from a button press webhook event — expires in 3 seconds',
		displayOptions: { show: { resource: ['form'], operation: ['create'] } },
		placeholder: '791a056b-006c-49dd-834b-c633fde52fe8',
		routing: { send: { type: 'body', property: 'trigger_id' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['form'], operation: ['create'] } },
		options: [
			{
				displayName: 'Callback ID',
				name: 'callbackId',
				type: 'string',
				default: "",
				description: 'Optional identifier for recognizing this view, which will be sent to your application when the user submits the form. Use this field, for example, to determine which form the user was supposed to fill out.',
				placeholder: 'timeoff_reguest_form',
				routing: { send: { type: 'body', property: 'callback_id' } },
			},
			{
				displayName: 'Close Text',
				name: 'closeText',
				type: 'string',
				default: "Cancel",
				description: 'Close button text',
				placeholder: 'Close',
				routing: { send: { type: 'body', property: 'close_text' } },
			},
			{
				displayName: 'Private Metadata',
				name: 'privateMetadata',
				type: 'string',
				default: "",
				description: 'Optional string that will be sent to your application when the user submits the form. Use this field, for example, to pass additional information in `JSON` format along with the form data.',
				placeholder: '{"timeoff_id":4378}',
				routing: { send: { type: 'body', property: 'private_metadata' } },
			},
			{
				displayName: 'Submit Text',
				name: 'submitText',
				type: 'string',
				default: "Submit",
				description: 'Submit button text',
				placeholder: 'Submit request',
				routing: { send: { type: 'body', property: 'submit_text' } },
			},
		],
	},
	{
		displayName: 'Builder Mode',
		name: 'formBuilderMode',
		type: 'options',
		options: [
			{ name: 'Visual Builder', value: 'builder' },
			{ name: 'JSON', value: 'json' },
		],
		default: 'builder',
		description: 'Build form visually or paste JSON',
		displayOptions: { show: { resource: ['form'], operation: ['create'] } },
	},
	{
		displayName: 'Form Blocks',
		name: 'formBlocks',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true, sortable: true },
		default: {},
		description: 'Add form blocks using the visual builder',
		displayOptions: { show: { resource: ['form'], operation: ['create'], formBuilderMode: ['builder'] } },
		options: [{
			name: 'block',
			displayName: 'Block',
			values: [
				{
					displayName: 'Allowed File Types',
					name: 'filetypes',
					type: 'string',
					default: '',
					placeholder: 'png,jpg,pdf',
					description: 'Comma-separated list of allowed file extensions',
					displayOptions: { show: { type: ['file_input'] } },
				},
				{
					displayName: 'Field Name',
					name: 'name',
					type: 'string',
					default: '',
					description: 'Unique field identifier (used in form submission data)',
					displayOptions: { show: { type: ['input', 'select', 'radio', 'checkbox', 'date', 'time', 'file_input'] } },
				},
				{
					displayName: 'Hint',
					name: 'hint',
					type: 'string',
					default: '',
					displayOptions: { show: { type: ['input', 'select', 'radio', 'checkbox', 'date', 'time', 'file_input'] } },
				},
				{
					displayName: 'Initial Date',
					name: 'initial_date',
					type: 'string',
					default: '',
					placeholder: '2024-01-01',
					displayOptions: { show: { type: ['date'] } },
				},
				{
					displayName: 'Initial Time',
					name: 'initial_time',
					type: 'string',
					default: '',
					placeholder: '09:00',
					displayOptions: { show: { type: ['time'] } },
				},
				{
					displayName: 'Initial Value',
					name: 'initial_value',
					type: 'string',
					default: '',
					displayOptions: { show: { type: ['input'] } },
				},
				{
					displayName: 'Label',
					name: 'label',
					type: 'string',
					default: '',
					displayOptions: { show: { type: ['input', 'select', 'radio', 'checkbox', 'date', 'time', 'file_input'] } },
				},
				{
					displayName: 'Max Files',
					name: 'max_files',
					type: 'number',
					default: 10,
					displayOptions: { show: { type: ['file_input'] } },
				},
				{
					displayName: 'Max Length',
					name: 'max_length',
					type: 'number',
					default: 0,
					displayOptions: { show: { type: ['input'] } },
				},
				{
					displayName: 'Min Length',
					name: 'min_length',
					type: 'number',
					default: 0,
					displayOptions: { show: { type: ['input'] } },
				},
				{
					displayName: 'Multiline',
					name: 'multiline',
					type: 'boolean',
					default: false,
					displayOptions: { show: { type: ['input'] } },
				},
				{
					displayName: 'Options',
					name: 'options',
					type: 'fixedCollection',
					typeOptions: { multipleValues: true },
					default: {},
					displayOptions: { show: { type: ['select', 'radio', 'checkbox'] } },
					options: [{
						name: 'option',
						displayName: 'Option',
						values: [
							{ displayName: 'Checked by Default', name: 'checked', type: 'boolean', default: false },
							{ displayName: 'Description', name: 'description', type: 'string', default: '' },
							{ displayName: 'Selected by Default', name: 'selected', type: 'boolean', default: false },
							{ displayName: 'Text', name: 'text', type: 'string', default: '' },
							{ displayName: 'Value', name: 'value', type: 'string', default: '' },
						],
					}],
				},
				{
					displayName: 'Placeholder',
					name: 'placeholder',
					type: 'string',
					default: '',
					displayOptions: { show: { type: ['input'] } },
				},
				{
					displayName: 'Required',
					name: 'required',
					type: 'boolean',
					default: false,
					displayOptions: { show: { type: ['input', 'select', 'radio', 'checkbox', 'date', 'time', 'file_input'] } },
				},
				{
					displayName: 'Text',
					name: 'text',
					type: 'string',
					default: '',
					displayOptions: { show: { type: ['header', 'plain_text', 'markdown'] } },
				},
				{
					displayName: 'Type',
					name: 'type',
					type: 'options',
					options: [
						{ name: '☑️ Checkboxes', value: 'checkbox' },
						{ name: '➖ Divider', value: 'divider' },
						{ name: '📄 Plain Text', value: 'plain_text' },
						{ name: '📅 Date Picker', value: 'date' },
						{ name: '📋 Select Dropdown', value: 'select' },
						{ name: '📎 File Upload', value: 'file_input' },
						{ name: '📝 Header', value: 'header' },
						{ name: '📝 Markdown', value: 'markdown' },
						{ name: '📝 Text Input', value: 'input' },
						{ name: '🔘 Radio Buttons', value: 'radio' },
						{ name: '🕐 Time Picker', value: 'time' },
					],
					default: 'input',
				},
			],
		}],
	},
	{
		displayName: 'Blocks (JSON)',
		name: 'formBlocks',
		type: 'json',
		required: true,
		default: '[]',
		description: 'Paste an array of blocks or the full form JSON from the <a href="https://dev.pachca.com/guides/forms/overview">visual form builder</a>',
		hint: 'Build your form visually at dev.pachca.com/guides/forms/overview, then paste the JSON here',
		placeholder: '{"title":"My form","blocks":[{"type":"input","name":"field_1","label":"Your name"}]}',
		displayOptions: { show: { resource: ['form'], operation: ['create'], formBuilderMode: ['json'] } },
	},
	{
		displayName: 'This operation is deprecated. In v2, use the Pachca Trigger node to receive form submissions via webhook, then process the data with standard n8n nodes.',
		name: 'processSubmissionNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['form'], operation: ['processSubmission'] } },
	},
	{
		displayName: 'Form Type',
		name: 'formType',
		type: 'options',
		options: [
			{ name: 'Auto-Detect', value: 'auto' },
			{ name: 'Feedback Form', value: 'feedback_form' },
			{ name: 'Task Request', value: 'task_request' },
			{ name: 'Timeoff Request', value: 'timeoff_request' },
		],
		default: 'auto',
		description: 'Form type for processing data',
		displayOptions: { show: { resource: ['form'], operation: ['processSubmission'] } },
	},
	{
		displayName: 'Validation Errors',
		name: 'validationErrors',
		type: 'json',
		default: '{}',
		description: 'Validation errors to send to user (JSON object with field names and messages)',
		displayOptions: { show: { resource: ['form'], operation: ['processSubmission'] } },
	},
];