import type { INodeProperties } from 'n8n-workflow';

export const groupTagOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['groupTag'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a group tag',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a group tag',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a group tag',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many group tags',
			},
			{
				name: 'Get Many Users',
				value: 'getAllUsers',
				action: 'Get many group tag users',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a group tag',
			},
		],
		default: 'getAll',
	},
];

export const groupTagFields: INodeProperties[] = [
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagCreateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['create'] } },
	},
	{
		displayName: 'Name',
		name: 'groupTagName',
		type: 'string',
		required: true,
		default: "",
		description: 'Tag name',
		displayOptions: { show: { resource: ['groupTag'], operation: ['create'] } },
		placeholder: 'New tag name',
	},
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagGetAllNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAll'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAll'] } },
	},
	{
		displayName: 'Names',
		name: 'names',
		type: 'string',
		default: "",
		description: 'Array of tag names to filter by',
		placeholder: 'Design,Product',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAll'] } },
	},
	{
		displayName: 'ID',
		name: 'groupTagId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['groupTag'], operation: ['get'] } },
		description: 'Tag ID',
	},
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagGetNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['get'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['groupTag'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'groupTagId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['groupTag'], operation: ['update'] } },
		description: 'Tag ID',
	},
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['update'] } },
	},
	{
		displayName: 'Name',
		name: 'groupTagName',
		type: 'string',
		required: true,
		default: "",
		description: 'Tag name',
		displayOptions: { show: { resource: ['groupTag'], operation: ['update'] } },
		placeholder: 'New tag name',
	},
	{
		displayName: 'ID',
		name: 'groupTagId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['groupTag'], operation: ['delete'] } },
		description: 'Tag ID',
	},
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagDeleteNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['delete'] } },
	},
	{
		displayName: 'ID',
		name: 'groupTagId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAllUsers'] } },
		description: 'Tag ID',
	},
	{
		displayName: 'Requires admin permissions',
		name: 'groupTagGetAllUsersNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAllUsers'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAllUsers'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAllUsers'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['groupTag'], operation: ['getAllUsers'] } },
	},
];