import type { INodeProperties } from 'n8n-workflow';

export const memberOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['member'] } },
		options: [
			{
				name: 'Add Group Tags',
				value: 'addGroupTags',
				action: 'Add group tags to chat member',
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a chat member',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a chat member',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many chat members',
			},
			{
				name: 'Leave',
				value: 'leave',
				action: 'Leave chat',
			},
			{
				name: 'Remove Group Tags',
				value: 'removeGroupTags',
				action: 'Remove group tags from chat member',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a chat member',
			},
		],
		default: 'getAll',
	},
];

export const memberFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['addGroupTags'] } },
	},
	{
		displayName: 'Group Tag IDs',
		name: 'groupTagIds',
		type: 'string',
		required: true,
		default: "",
		description: 'Array of tag IDs to be added as members',
		displayOptions: { show: { resource: ['member'], operation: ['addGroupTags'] } },
		placeholder: '86,18',
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['removeGroupTags'] } },
	},
	{
		displayName: 'Tag ID',
		name: 'tagId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['member'], operation: ['removeGroupTags'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['leave'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['getAll'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['member'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['member'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['member'], operation: ['getAll'] } },
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		options: [{ name: 'Admin', value: 'admin' },
{ name: 'All', value: 'all', description: 'Any role' },
{ name: 'Editor', value: 'editor' },
{ name: 'Member', value: 'member', description: 'Member/subscriber' },
{ name: 'Owner', value: 'owner' }],
		default: "",
		description: 'Role in the chat',
		displayOptions: { show: { resource: ['member'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'role' } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID (conversation, channel, or thread chat)',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['create'] } },
	},
	{
		displayName: 'Member IDs',
		name: 'memberIds',
		type: 'string',
		required: true,
		default: "",
		description: 'Array of user IDs who will become members',
		displayOptions: { show: { resource: ['member'], operation: ['create'] } },
		placeholder: '186,187',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['member'], operation: ['create'] } },
		options: [
			{
				displayName: 'Silent',
				name: 'silent',
				type: 'boolean',
				default: false,
				description: 'Whether to do not create a system message in the chat about adding a member',
				routing: { send: { type: 'body', property: 'silent' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['delete'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchUsers', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 186',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/users/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/users/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/users/(\\d+)', errorMessage: 'Not a valid Pachca user URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['delete'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'Chat ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['update'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchUsers', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 186',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/users/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/users/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/users/(\\d+)', errorMessage: 'Not a valid Pachca user URL' } }],
			},
		],
		displayOptions: { show: { resource: ['member'], operation: ['update'] } },
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		required: true,
		options: [{ name: 'Admin', value: 'admin' },
{ name: 'Editor', value: 'editor', description: 'Editor (available for channels only)' },
{ name: 'Member', value: 'member', description: 'Member or subscriber' }],
		default: "member",
		displayOptions: { show: { resource: ['member'], operation: ['update'] } },
		routing: { send: { type: 'body', property: 'role' } },
	},
];