import type { INodeProperties } from 'n8n-workflow';

export const messageOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['message'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a message',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a message',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a message',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many messages',
			},
			{
				name: 'Pin',
				value: 'pin',
				action: 'Pin a message',
			},
			{
				name: 'Unpin',
				value: 'unpin',
				action: 'Unpin a message',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a message',
			},
		],
		default: 'create',
	},
];

export const messageFields: INodeProperties[] = [
	{
		displayName: 'Entity Type',
		name: 'entityType',
		type: 'options',
		required: true,
		options: [{ name: 'Discussion', value: 'discussion', description: 'Conversation or channel' },
{ name: 'Thread', value: 'thread' },
{ name: 'User', value: 'user' }],
		default: "discussion",
		displayOptions: { show: { resource: ['message'], operation: ['create'] } },
	},
	{
		displayName: 'Entity ID',
		name: 'entityId',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchEntities', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 334',
			},
		],
		displayOptions: { show: { resource: ['message'], operation: ['create'] } },
	},
	{
		displayName: 'Content',
		name: 'content',
		type: 'string',
		required: true,
		typeOptions: { rows: 4 },
		default: "",
		description: 'Message text. Supports mentions: `@nickname` or `&lt;@user_id&gt;` (automatically converted to `@nickname`).',
		displayOptions: { show: { resource: ['message'], operation: ['create'] } },
		placeholder: 'Yesterday we sold 756 t-shirts (10% more than last Sunday)',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['create'] } },
		options: [
			{
				displayName: 'Display Avatar URL',
				name: 'displayAvatarUrl',
				type: 'string',
				default: "",
				description: 'Custom sender avatar URL for this message. This field can only be used with a bot access_token.',
				placeholder: 'https://example.com/avatar.png',
			},
			{
				displayName: 'Display Name',
				name: 'displayName',
				type: 'string',
				default: "",
				description: 'Custom sender display name for this message. This field can only be used with a bot access_token.',
				placeholder: 'Support Bot',
			},
			{
				displayName: 'Files',
				name: 'files',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'file',
					displayName: 'File',
					values: [
						{
							displayName: 'File Type',
							name: 'file_type',
							type: 'options',
							options: [{ name: 'File', value: 'file', description: 'Regular file' },
{ name: 'Image', value: 'image' }],
							default: "",
						},
						{
							displayName: 'Height',
							name: 'height',
							type: 'number',
							default: 0,
							description: 'Image height in px (used when file_type is set to image)',
						},
						{
							displayName: 'Key',
							name: 'key',
							type: 'string',
							default: "",
							description: 'File path obtained from [file upload](POST /direct_url)',
						},
						{
							displayName: 'Name',
							name: 'name',
							type: 'string',
							default: "",
							description: 'File name to display to the user (recommended to include the file extension)',
						},
						{
							displayName: 'Size',
							name: 'size',
							type: 'number',
							default: 0,
							description: 'File size in bytes, displayed to the user',
						},
						{
							displayName: 'Width',
							name: 'width',
							type: 'number',
							default: 0,
							description: 'Image width in px (used when file_type is set to image)',
						},
					],
				}],
				default: [],
				description: 'Files to attach',
				hint: 'Upload a file first using File > Create, then use the returned key here',
			},
			{
				displayName: 'Link Preview',
				name: 'linkPreview',
				type: 'boolean',
				default: false,
				description: 'Whether to display a preview of the first link found in the message text',
			},
			{
				displayName: 'Parent Message ID',
				name: 'parentMessageId',
				type: 'number',
				default: 0,
				description: 'Message ID. Specify when sending a reply to another message.',
				placeholder: '194270',
			},
			{
				displayName: 'Skip Invite Mentions',
				name: 'skipInviteMentions',
				type: 'boolean',
				default: false,
				description: 'Whether to skip adding mentioned users to the thread. Only works when sending a message to a thread.',
			},
		],
	},
	{
		displayName: 'Button Layout',
		name: 'buttonLayout',
		type: 'options',
		options: [
			{ name: 'None', value: 'none' },
			{ name: 'Single Row', value: 'single_row' },
			{ name: 'Multiple Rows', value: 'multiple_rows' },
			{ name: 'Raw JSON', value: 'raw_json' },
		],
		default: 'none',
		description: 'How to layout buttons in the message',
		displayOptions: { show: { resource: ['message'], operation: ['create'] } },
	},
	{
		displayName: 'Buttons',
		name: 'buttons',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		options: [{
			name: 'button',
			displayName: 'Button',
			values: [
				{
					displayName: 'Text',
					name: 'text',
					type: 'string',
					default: '',
					description: 'Button label (max 255 characters)',
					placeholder: 'Click me',
				},
				{
					displayName: 'Type',
					name: 'type',
					type: 'options',
					options: [
						{ name: 'Data (Webhook)', value: 'data' },
						{ name: 'URL (Link)', value: 'url' },
					],
					default: 'data',
					description: 'Data sends a webhook on click, URL opens a link',
				},
				{
					displayName: 'Data',
					name: 'data',
					type: 'string',
					default: '',
					description: 'Data sent via webhook when button is clicked (max 255 characters)',
					placeholder: 'action_confirm',
					displayOptions: { show: { type: ['data'] } },
				},
				{
					displayName: 'URL',
					name: 'url',
					type: 'string',
					default: '',
					description: 'URL to open when button is clicked',
					placeholder: 'https://example.com',
					displayOptions: { show: { type: ['url'] } },
				},
			],
		}],
		default: {},
		description: 'Buttons to add to the message. Max 100 buttons, up to 8 per row.',
		displayOptions: { show: { resource: ['message'], operation: ['create'], buttonLayout: ['single_row', 'multiple_rows'] } },
	},
	{
		displayName: 'Buttons (JSON)',
		name: 'rawJsonButtons',
		type: 'json',
		default: '[]',
		description: 'Buttons as JSON: array of rows, each row is an array of buttons. To remove all buttons, send [].',
		placeholder: '[[{"text":"OK","data":"confirm"}],[{"text":"Link","url":"https://example.com"}]]',
		displayOptions: { show: { resource: ['message'], operation: ['create'], buttonLayout: ['raw_json'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['message'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'Chat ID',
		name: 'chatId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		description: 'Chat ID (conversation, channel, direct message, or thread chat)',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchChats', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 198',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/chats/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/chats/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/chats/(\\d+)', errorMessage: 'Not a valid Pachca chat URL' } }],
			},
		],
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'Sort',
		name: 'sort',
		type: 'options',
		options: [{ name: 'ID', value: 'id', description: 'By message ID' }],
		default: "id",
		description: 'Sort field',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'options',
		options: [{ name: 'Ascending', value: 'asc' },
{ name: 'Descending', value: 'desc' }],
		default: "desc",
		description: 'Sort direction',
		displayOptions: { show: { resource: ['message'], operation: ['getAll'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['message'], operation: ['get'] } },
		description: 'Message ID',
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['message'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['message'], operation: ['update'] } },
		description: 'Message ID',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['update'] } },
		options: [
			{
				displayName: 'Content',
				name: 'content',
				type: 'string',
				typeOptions: { rows: 4 },
				default: "",
				description: 'Message text. Supports mentions: `@nickname` or `&lt;@user_id&gt;` (automatically converted to `@nickname`).',
				placeholder: 'Try to spell these correctly on the first attempt: bureaucracy, accommodate, definitely, entrepreneur, liaison, necessary, surveillance, questionnaire.',
			},
			{
				displayName: 'Display Avatar URL',
				name: 'displayAvatarUrl',
				type: 'string',
				default: "",
				description: 'Custom sender avatar URL for this message. This field can only be used with a bot access_token.',
				placeholder: 'https://example.com/avatar.png',
			},
			{
				displayName: 'Display Name',
				name: 'displayName',
				type: 'string',
				default: "",
				description: 'Custom sender display name for this message. This field can only be used with a bot access_token.',
				placeholder: 'Support Bot',
			},
			{
				displayName: 'Files',
				name: 'files',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'file',
					displayName: 'File',
					values: [
						{
							displayName: 'File Type',
							name: 'file_type',
							type: 'string',
							default: "",
							description: 'File type: file (file), image (image)',
						},
						{
							displayName: 'Height',
							name: 'height',
							type: 'number',
							default: 0,
							description: 'Image height in px (used when file_type is set to image)',
						},
						{
							displayName: 'Key',
							name: 'key',
							type: 'string',
							default: "",
							description: 'File path obtained from [file upload](POST /direct_url)',
						},
						{
							displayName: 'Name',
							name: 'name',
							type: 'string',
							default: "",
							description: 'File name to display to the user (recommended to include the file extension)',
						},
						{
							displayName: 'Size',
							name: 'size',
							type: 'number',
							default: 0,
							description: 'File size in bytes, displayed to the user',
						},
						{
							displayName: 'Width',
							name: 'width',
							type: 'number',
							default: 0,
							description: 'Image width in px (used when file_type is set to image)',
						},
					],
				}],
				default: [],
				description: 'Files to attach',
				hint: 'Upload a file first using File > Create, then use the returned key here',
			},
		],
	},
	{
		displayName: 'Button Layout',
		name: 'buttonLayout',
		type: 'options',
		options: [
			{ name: 'None', value: 'none' },
			{ name: 'Single Row', value: 'single_row' },
			{ name: 'Multiple Rows', value: 'multiple_rows' },
			{ name: 'Raw JSON', value: 'raw_json' },
		],
		default: 'none',
		description: 'How to layout buttons in the message',
		displayOptions: { show: { resource: ['message'], operation: ['update'] } },
	},
	{
		displayName: 'Buttons',
		name: 'buttons',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		options: [{
			name: 'button',
			displayName: 'Button',
			values: [
				{
					displayName: 'Text',
					name: 'text',
					type: 'string',
					default: '',
					description: 'Button label (max 255 characters)',
					placeholder: 'Click me',
				},
				{
					displayName: 'Type',
					name: 'type',
					type: 'options',
					options: [
						{ name: 'Data (Webhook)', value: 'data' },
						{ name: 'URL (Link)', value: 'url' },
					],
					default: 'data',
					description: 'Data sends a webhook on click, URL opens a link',
				},
				{
					displayName: 'Data',
					name: 'data',
					type: 'string',
					default: '',
					description: 'Data sent via webhook when button is clicked (max 255 characters)',
					placeholder: 'action_confirm',
					displayOptions: { show: { type: ['data'] } },
				},
				{
					displayName: 'URL',
					name: 'url',
					type: 'string',
					default: '',
					description: 'URL to open when button is clicked',
					placeholder: 'https://example.com',
					displayOptions: { show: { type: ['url'] } },
				},
			],
		}],
		default: {},
		description: 'Buttons to add to the message. Max 100 buttons, up to 8 per row.',
		displayOptions: { show: { resource: ['message'], operation: ['update'], buttonLayout: ['single_row', 'multiple_rows'] } },
	},
	{
		displayName: 'Buttons (JSON)',
		name: 'rawJsonButtons',
		type: 'json',
		default: '[]',
		description: 'Buttons as JSON: array of rows, each row is an array of buttons. To remove all buttons, send [].',
		placeholder: '[[{"text":"OK","data":"confirm"}],[{"text":"Link","url":"https://example.com"}]]',
		displayOptions: { show: { resource: ['message'], operation: ['update'], buttonLayout: ['raw_json'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['message'], operation: ['delete'] } },
		description: 'Message ID',
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['message'], operation: ['pin'] } },
		description: 'Message ID',
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['message'], operation: ['unpin'] } },
		description: 'Message ID',
	},
];