import type { INodeProperties } from 'n8n-workflow';

export const reactionOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['reaction'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a reaction',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a reaction',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many reactions',
			},
		],
		default: 'create',
	},
];

export const reactionFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'reactionsMessageId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['reaction'], operation: ['create'] } },
		description: 'Message ID',
	},
	{
		displayName: 'Code',
		name: 'reactionsReactionCode',
		type: 'string',
		required: true,
		default: "",
		description: 'Reaction emoji character',
		displayOptions: { show: { resource: ['reaction'], operation: ['create'] } },
		placeholder: '👍',
		routing: { send: { type: 'body', property: 'code' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['reaction'], operation: ['create'] } },
		options: [
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: "",
				description: 'Emoji text name (used for custom emoji)',
				placeholder: ':+1:',
				routing: { send: { type: 'body', property: 'name' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'reactionsMessageId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['reaction'], operation: ['delete'] } },
		description: 'Message ID',
	},
	{
		displayName: 'Code',
		name: 'reactionsReactionCode',
		type: 'string',
		default: "",
		description: 'Emoji character of the reaction',
		placeholder: '👍',
		displayOptions: { show: { resource: ['reaction'], operation: ['delete'] } },
		routing: { send: { type: 'query', property: 'code' } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: "",
		description: 'Text name of the emoji (used for custom emoji)',
		placeholder: ':+1:',
		displayOptions: { show: { resource: ['reaction'], operation: ['delete'] } },
		routing: { send: { type: 'query', property: 'name' } },
	},
	{
		displayName: 'ID',
		name: 'reactionsMessageId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['reaction'], operation: ['getAll'] } },
		description: 'Message ID',
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['reaction'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['reaction'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['reaction'], operation: ['getAll'] } },
	},
];