import type { INodeProperties } from 'n8n-workflow';

export const searchOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['search'] } },
		options: [
			{
				name: 'Get Many Chats',
				value: 'getAllChats',
				action: 'Search chats',
			},
			{
				name: 'Get Many Messages',
				value: 'getAllMessages',
				action: 'Search messages',
			},
			{
				name: 'Get Many Users',
				value: 'getAllUsers',
				action: 'Search users',
			},
		],
		default: 'getAllChats',
	},
];

export const searchFields: INodeProperties[] = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['search'], operation: ['getAllChats'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 100 },
		displayOptions: { show: { resource: ['search'], operation: ['getAllChats'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['search'], operation: ['getAllChats'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: "",
		description: 'Search query text',
		placeholder: 'Development',
		displayOptions: { show: { resource: ['search'], operation: ['getAllChats'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['search'], operation: ['getAllChats'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by chat activity',
			},
			{
				displayName: 'Chat Subtype',
				name: 'chatSubtype',
				type: 'options',
				options: [{ name: 'Discussion', value: 'discussion', description: 'Channel or conversation' },
{ name: 'Thread', value: 'thread' }],
				default: "",
				description: 'Filter by chat type',
			},
			{
				displayName: 'Created From',
				name: 'createdFrom',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (from)',
				placeholder: '2025-01-01T00:00:00.000Z',
			},
			{
				displayName: 'Created To',
				name: 'createdTo',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (to)',
				placeholder: '2025-02-01T00:00:00.000Z',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'options',
				options: [{ name: 'Ascending', value: 'asc' },
{ name: 'Descending', value: 'desc' }],
				default: "",
				description: 'Sort direction',
			},
			{
				displayName: 'Personal',
				name: 'personal',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by direct chats',
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['search'], operation: ['getAllMessages'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: { show: { resource: ['search'], operation: ['getAllMessages'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['search'], operation: ['getAllMessages'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: "",
		description: 'Search query text',
		placeholder: 't-shirts',
		displayOptions: { show: { resource: ['search'], operation: ['getAllMessages'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['search'], operation: ['getAllMessages'] } },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by chat activity',
			},
			{
				displayName: 'Chat IDs',
				name: 'chatIds',
				type: 'string',
				default: "",
				description: 'Filter by chat IDs',
				placeholder: '198,334',
			},
			{
				displayName: 'Created From',
				name: 'createdFrom',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (from)',
				placeholder: '2025-01-01T00:00:00.000Z',
			},
			{
				displayName: 'Created To',
				name: 'createdTo',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (to)',
				placeholder: '2025-02-01T00:00:00.000Z',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'options',
				options: [{ name: 'Ascending', value: 'asc' },
{ name: 'Descending', value: 'desc' }],
				default: "",
				description: 'Sort direction',
			},
			{
				displayName: 'User IDs',
				name: 'userIds',
				type: 'string',
				default: "",
				description: 'Filter by message author IDs',
				placeholder: '12,185',
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['search'], operation: ['getAllUsers'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 200 },
		displayOptions: { show: { resource: ['search'], operation: ['getAllUsers'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['search'], operation: ['getAllUsers'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: "",
		description: 'Search query text',
		placeholder: 'Oleg',
		displayOptions: { show: { resource: ['search'], operation: ['getAllUsers'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['search'], operation: ['getAllUsers'] } },
		options: [
			{
				displayName: 'Company Roles',
				name: 'companyRoles',
				type: 'string',
				default: "",
				description: 'Filter by employee roles',
				placeholder: 'admin,user',
			},
			{
				displayName: 'Created From',
				name: 'createdFrom',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (from)',
				placeholder: '2025-01-01T00:00:00.000Z',
			},
			{
				displayName: 'Created To',
				name: 'createdTo',
				type: 'dateTime',
				default: "",
				description: 'Filter by creation date (to)',
				placeholder: '2025-02-01T00:00:00.000Z',
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'options',
				options: [{ name: 'Ascending', value: 'asc' },
{ name: 'Descending', value: 'desc' }],
				default: "",
				description: 'Sort direction',
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				options: [{ name: 'Alphabetical', value: 'alphabetical', description: 'Alphabetically' },
{ name: 'By Score', value: 'by_score', description: 'By relevance' }],
				default: "",
				description: 'Sort results by',
			},
		],
	},
];