import type { INodeProperties } from 'n8n-workflow';

export const securityOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['security'] } },
		options: [
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many audit events',
			},
		],
		default: 'getAll',
	},
];

export const securityFields: INodeProperties[] = [
	{
		displayName: 'Requires owner role and the "Corporation" plan',
		name: 'securityGetAllNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['security'], operation: ['getAll'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['security'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['security'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['security'], operation: ['getAll'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['security'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Actor ID',
				name: 'actorId',
				type: 'string',
				default: "",
				description: 'ID of the user who performed the action',
				placeholder: '98765',
			},
			{
				displayName: 'Actor Type',
				name: 'actorType',
				type: 'string',
				default: "",
				placeholder: 'User',
			},
			{
				displayName: 'End Time',
				name: 'endTime',
				type: 'dateTime',
				default: "",
				description: 'End timestamp (exclusive)',
				placeholder: '2025-05-02T09:11:00Z',
			},
			{
				displayName: 'Entity ID',
				name: 'entityId',
				type: 'string',
				default: "",
				description: 'ID of the affected entity',
				placeholder: '98765',
			},
			{
				displayName: 'Entity Type',
				name: 'entityType',
				type: 'string',
				default: "",
				placeholder: 'User',
			},
			{
				displayName: 'Event Key',
				name: 'eventKey',
				type: 'options',
				options: [{ name: 'Access Token Created', value: 'access_token_created', description: 'New access token created' },
{ name: 'Access Token Destroy', value: 'access_token_destroy', description: 'Access token deleted' },
{ name: 'Access Token Updated', value: 'access_token_updated' },
{ name: 'Audit Events Accessed', value: 'audit_events_accessed', description: 'Audit logs accessed' },
{ name: 'Chat Created', value: 'chat_created', description: 'New chat created' },
{ name: 'Chat Permission Changed', value: 'chat_permission_changed', description: 'Chat access permissions changed' },
{ name: 'Chat Renamed', value: 'chat_renamed' },
{ name: 'Dlp Violation Detected', value: 'dlp_violation_detected', description: 'DLP rule violation detected' },
{ name: 'Kms Decrypt', value: 'kms_decrypt', description: 'Data decrypted' },
{ name: 'Kms Encrypt', value: 'kms_encrypt', description: 'Data encrypted' },
{ name: 'Message Created', value: 'message_created' },
{ name: 'Message Deleted', value: 'message_deleted' },
{ name: 'Message Updated', value: 'message_updated', description: 'Message edited' },
{ name: 'Reaction Created', value: 'reaction_created', description: 'Reaction added' },
{ name: 'Reaction Deleted', value: 'reaction_deleted', description: 'Reaction removed' },
{ name: 'Search Chats Api', value: 'search_chats_api', description: 'Chat search via API' },
{ name: 'Search Messages Api', value: 'search_messages_api', description: 'Message search via API' },
{ name: 'Search Users Api', value: 'search_users_api', description: 'Employee search via API' },
{ name: 'Tag Added To Chat', value: 'tag_added_to_chat' },
{ name: 'Tag Created', value: 'tag_created', description: 'New tag created' },
{ name: 'Tag Deleted', value: 'tag_deleted' },
{ name: 'Tag Removed From Chat', value: 'tag_removed_from_chat' },
{ name: 'Thread Created', value: 'thread_created' },
{ name: 'User 2fa Fail', value: 'user_2fa_fail', description: 'Failed two-factor authentication attempt' },
{ name: 'User 2fa Success', value: 'user_2fa_success', description: 'Successful two-factor authentication' },
{ name: 'User Added To Tag', value: 'user_added_to_tag' },
{ name: 'User Chat Join', value: 'user_chat_join', description: 'User joined the chat' },
{ name: 'User Chat Leave', value: 'user_chat_leave', description: 'User left the chat' },
{ name: 'User Created', value: 'user_created', description: 'New user account created' },
{ name: 'User Deleted', value: 'user_deleted', description: 'User account deleted' },
{ name: 'User Login', value: 'user_login', description: 'User logged in successfully' },
{ name: 'User Logout', value: 'user_logout', description: 'User logged out' },
{ name: 'User Removed From Tag', value: 'user_removed_from_tag' },
{ name: 'User Role Changed', value: 'user_role_changed' },
{ name: 'User Updated', value: 'user_updated', description: 'User data updated' }],
				default: "",
				description: 'Filter by specific event type',
			},
			{
				displayName: 'Start Time',
				name: 'startTime',
				type: 'dateTime',
				default: "",
				description: 'Start timestamp (inclusive)',
				placeholder: '2025-05-01T09:11:00Z',
			},
		],
	},
];