import type { INodeProperties } from 'n8n-workflow';

export const taskOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['task'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a task',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a task',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a task',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many tasks',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a task',
			},
		],
		default: 'create',
	},
];

export const taskFields: INodeProperties[] = [
	{
		displayName: 'Kind',
		name: 'taskKind',
		type: 'options',
		required: true,
		options: [{ name: 'Call', value: 'call', description: 'Call a contact' },
{ name: 'Email', value: 'email', description: 'Send an email' },
{ name: 'Event', value: 'event' },
{ name: 'Meeting', value: 'meeting' },
{ name: 'Reminder', value: 'reminder', description: 'Simple reminder' }],
		default: "call",
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'kind' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['task'], operation: ['create'] } },
		options: [
			{
				displayName: 'All Day',
				name: 'allDay',
				type: 'boolean',
				default: false,
				description: 'Whether to all-day task (without specific time)',
				routing: { send: { type: 'body', property: 'all_day' } },
			},
			{
				displayName: 'Chat ID',
				name: 'chatId',
				type: 'number',
				default: 0,
				description: 'ID of the chat to link the task to',
				placeholder: '456',
				routing: { send: { type: 'body', property: 'chat_id' } },
			},
			{
				displayName: 'Content',
				name: 'taskContent',
				type: 'string',
				typeOptions: { rows: 4 },
				default: "",
				description: 'Description (defaults to the kind name)',
				placeholder: 'Pick up 21 orders from the warehouse',
				routing: { send: { type: 'body', property: 'content' } },
			},
			{
				displayName: 'Custom Properties',
				name: 'customProperties',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'property',
					displayName: 'Custom Property',
					values: [
						{
							displayName: 'Custom Property Name or ID',
							name: 'id',
							type: 'options',
							typeOptions: { loadOptionsMethod: 'getCustomProperties' },
							default: '',
							description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: "",
							description: 'Value to set',
						},
					],
				}],
				default: [],
				description: 'Custom properties to set',
				routing: { send: { type: 'body', property: 'custom_properties' } },
			},
			{
				displayName: 'Due At',
				name: 'taskDueAt',
				type: 'dateTime',
				default: "",
				description: 'Task due date (ISO-8601) in YYYY-MM-DDThh:mm:ss.sssTZD format. If the time is set to 23:59:59.000, the task will be created as an all-day task (without specific time).',
				placeholder: '2020-06-05T12:00:00.000+03:00',
				routing: { send: { type: 'body', property: 'due_at' } },
			},
			{
				displayName: 'Performer IDs',
				name: 'performerIds',
				type: 'string',
				default: "",
				description: 'Array of user IDs to assign as task performers (defaults to you)',
				placeholder: '12,13',
			},
			{
				displayName: 'Priority',
				name: 'taskPriority',
				type: 'number',
				default: 1,
				description: 'Priority: 1, 2 (important), or 3 (very important)',
				placeholder: '2',
				routing: { send: { type: 'body', property: 'priority' } },
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['task'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['task'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['task'], operation: ['getAll'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['task'], operation: ['get'] } },
		description: 'Task ID',
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['task'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['task'], operation: ['update'] } },
		description: 'Task ID',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['task'], operation: ['update'] } },
		options: [
			{
				displayName: 'All Day',
				name: 'allDay',
				type: 'boolean',
				default: false,
				description: 'Whether to all-day task (without specific time)',
				routing: { send: { type: 'body', property: 'all_day' } },
			},
			{
				displayName: 'Content',
				name: 'content',
				type: 'string',
				typeOptions: { rows: 4 },
				default: "",
				description: 'Description',
				placeholder: 'Pick up 21 orders from the warehouse',
				routing: { send: { type: 'body', property: 'content' } },
			},
			{
				displayName: 'Custom Properties',
				name: 'customProperties',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'property',
					displayName: 'Custom Property',
					values: [
						{
							displayName: 'Custom Property Name or ID',
							name: 'id',
							type: 'options',
							typeOptions: { loadOptionsMethod: 'getCustomProperties' },
							default: '',
							description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: "",
							description: 'Value to set',
						},
					],
				}],
				default: [],
				description: 'Custom properties to set',
				routing: { send: { type: 'body', property: 'custom_properties' } },
			},
			{
				displayName: 'Done At',
				name: 'doneAt',
				type: 'dateTime',
				default: "",
				description: 'Task completion date and time (ISO-8601, UTC+0) in YYYY-MM-DDThh:mm:ss.sssZ format',
				placeholder: '2020-06-05T12:00:00.000Z',
				routing: { send: { type: 'body', property: 'done_at' } },
			},
			{
				displayName: 'Due At',
				name: 'dueAt',
				type: 'dateTime',
				default: "",
				description: 'Task due date (ISO-8601) in YYYY-MM-DDThh:mm:ss.sssTZD format. If the time is set to 23:59:59.000, the task will be created as an all-day task (without specific time).',
				placeholder: '2020-06-05T12:00:00.000+03:00',
				routing: { send: { type: 'body', property: 'due_at' } },
			},
			{
				displayName: 'Kind',
				name: 'kind',
				type: 'options',
				options: [{ name: 'Call', value: 'call', description: 'Call a contact' },
{ name: 'Email', value: 'email', description: 'Send an email' },
{ name: 'Event', value: 'event' },
{ name: 'Meeting', value: 'meeting' },
{ name: 'Reminder', value: 'reminder', description: 'Simple reminder' }],
				default: "call",
				routing: { send: { type: 'body', property: 'kind' } },
			},
			{
				displayName: 'Performer IDs',
				name: 'performerIds',
				type: 'string',
				default: "",
				description: 'Array of user IDs to assign as task performers',
				placeholder: '12',
			},
			{
				displayName: 'Priority',
				name: 'priority',
				type: 'number',
				default: 0,
				description: 'Priority: 1, 2 (important), or 3 (very important)',
				placeholder: '2',
				routing: { send: { type: 'body', property: 'priority' } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [{ name: 'Done', value: 'done' },
{ name: 'Undone', value: 'undone', description: 'Active' }],
				default: "done",
				routing: { send: { type: 'body', property: 'status' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['task'], operation: ['delete'] } },
		description: 'Task ID',
	},
];