import type { INodeProperties } from 'n8n-workflow';

export const userOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['user'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a user',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a user',
			},
			{
				name: 'Delete Avatar',
				value: 'deleteAvatar',
				action: 'Delete user avatar',
			},
			{
				name: 'Delete Status',
				value: 'deleteStatus',
				action: 'Delete user status',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a user',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many users',
			},
			{
				name: 'Get Status',
				value: 'getStatus',
				action: 'Get user status',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a user',
			},
			{
				name: 'Update Avatar',
				value: 'updateAvatar',
				action: 'Update user avatar',
			},
			{
				name: 'Update Status',
				value: 'updateStatus',
				action: 'Update user status',
			},
		],
		default: 'getAll',
	},
];

export const userFields: INodeProperties[] = [
	{
		displayName: 'Requires admin permissions',
		name: 'userCreateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		default: "",
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
		placeholder: 'olegp@example.com',
		routing: { send: { type: 'body', property: 'email' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
		options: [
			{
				displayName: 'Custom Properties',
				name: 'customProperties',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'property',
					displayName: 'Custom Property',
					values: [
						{
							displayName: 'Custom Property Name or ID',
							name: 'id',
							type: 'options',
							typeOptions: { loadOptionsMethod: 'getCustomProperties' },
							default: '',
							description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: "",
							description: 'Value to set',
						},
					],
				}],
				default: [],
				description: 'Custom properties to set',
				routing: { send: { type: 'body', property: 'custom_properties' } },
			},
			{
				displayName: 'Department',
				name: 'department',
				type: 'string',
				default: "",
				placeholder: 'Product',
				routing: { send: { type: 'body', property: 'department' } },
			},
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: "",
				placeholder: 'Oleg',
				routing: { send: { type: 'body', property: 'first_name' } },
			},
			{
				displayName: 'Last Name',
				name: 'lastName',
				type: 'string',
				default: "",
				placeholder: 'Petrov',
				routing: { send: { type: 'body', property: 'last_name' } },
			},
			{
				displayName: 'List Tags',
				name: 'listTags',
				type: 'string',
				default: "",
				description: 'Array of tags to assign to the employee',
				placeholder: 'Product,Design',
			},
			{
				displayName: 'Nickname',
				name: 'nickname',
				type: 'string',
				default: "",
				description: 'Username',
				placeholder: 'olegpetrov',
				routing: { send: { type: 'body', property: 'nickname' } },
			},
			{
				displayName: 'Phone Number',
				name: 'phoneNumber',
				type: 'string',
				default: "",
				placeholder: '+79001234567',
				routing: { send: { type: 'body', property: 'phone_number' } },
			},
			{
				displayName: 'Role',
				name: 'role',
				type: 'options',
				options: [{ name: 'Admin', value: 'admin', description: 'Administrator' },
{ name: 'Multi Guest', value: 'multi_guest', description: 'Multi-guest' },
{ name: 'User', value: 'user', description: 'Employee' }],
				default: "user",
				description: 'Access level',
				routing: { send: { type: 'body', property: 'role' } },
			},
			{
				displayName: 'Skip Email Notify',
				name: 'skipEmailNotify',
				type: 'boolean',
				default: false,
				description: 'Whether to skip sending an invitation to the employee. The employee will not receive an email invitation to create an account. Useful when pre-creating accounts before SSO login.',
				routing: { send: { type: 'body', property: 'skip_email_notify' } },
			},
			{
				displayName: 'Suspended',
				name: 'suspended',
				type: 'boolean',
				default: false,
				description: 'Whether to user deactivated',
				routing: { send: { type: 'body', property: 'suspended' } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: "",
				description: 'Job title',
				placeholder: 'CIO',
				routing: { send: { type: 'body', property: 'title' } },
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['user'], operation: ['getAll'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		description: 'Max number of results to return',
		typeOptions: { minValue: 1, maxValue: 50 },
		displayOptions: { show: { resource: ['user'], operation: ['getAll'], returnAll: [false] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['user'], operation: ['getAll'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: "",
		description: 'Search phrase to filter results. Search works on the following fields: `first_name`, `last_name`, `email`, `phone_number`, and `nickname`.',
		placeholder: 'Oleg',
		displayOptions: { show: { resource: ['user'], operation: ['getAll'] } },
		routing: { send: { type: 'query', property: 'query' } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'User ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchUsers', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 12',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/users/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/users/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/users/(\\d+)', errorMessage: 'Not a valid Pachca user URL' } }],
			},
		],
		displayOptions: { show: { resource: ['user'], operation: ['get'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['user'], operation: ['get'] } },
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'User ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchUsers', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 12',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/users/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/users/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/users/(\\d+)', errorMessage: 'Not a valid Pachca user URL' } }],
			},
		],
		displayOptions: { show: { resource: ['user'], operation: ['update'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userUpdateNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['update'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['user'], operation: ['update'] } },
		options: [
			{
				displayName: 'Custom Properties',
				name: 'customProperties',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				options: [{
					name: 'property',
					displayName: 'Custom Property',
					values: [
						{
							displayName: 'Custom Property Name or ID',
							name: 'id',
							type: 'options',
							typeOptions: { loadOptionsMethod: 'getCustomProperties' },
							default: '',
							description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
						},
						{
							displayName: 'Value',
							name: 'value',
							type: 'string',
							default: "",
							description: 'Value to set',
						},
					],
				}],
				default: [],
				description: 'Custom properties to set',
				routing: { send: { type: 'body', property: 'custom_properties' } },
			},
			{
				displayName: 'Department',
				name: 'department',
				type: 'string',
				default: "",
				placeholder: 'Engineering',
				routing: { send: { type: 'body', property: 'department' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: "",
				placeholder: 'olegpetrov@example.com',
				routing: { send: { type: 'body', property: 'email' } },
			},
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: "",
				placeholder: 'Oleg',
				routing: { send: { type: 'body', property: 'first_name' } },
			},
			{
				displayName: 'Last Name',
				name: 'lastName',
				type: 'string',
				default: "",
				placeholder: 'Petrov',
				routing: { send: { type: 'body', property: 'last_name' } },
			},
			{
				displayName: 'List Tags',
				name: 'listTags',
				type: 'string',
				default: "",
				description: 'Array of tags to assign to the employee',
				placeholder: 'Product',
			},
			{
				displayName: 'Nickname',
				name: 'nickname',
				type: 'string',
				default: "",
				description: 'Username',
				placeholder: 'olegpetrov',
				routing: { send: { type: 'body', property: 'nickname' } },
			},
			{
				displayName: 'Phone Number',
				name: 'phoneNumber',
				type: 'string',
				default: "",
				placeholder: '+79001234567',
				routing: { send: { type: 'body', property: 'phone_number' } },
			},
			{
				displayName: 'Role',
				name: 'role',
				type: 'options',
				options: [{ name: 'Admin', value: 'admin', description: 'Administrator' },
{ name: 'Multi Guest', value: 'multi_guest', description: 'Multi-guest' },
{ name: 'User', value: 'user', description: 'Employee' }],
				default: "user",
				description: 'Access level',
				routing: { send: { type: 'body', property: 'role' } },
			},
			{
				displayName: 'Suspended',
				name: 'suspended',
				type: 'boolean',
				default: false,
				description: 'Whether to user deactivated',
				routing: { send: { type: 'body', property: 'suspended' } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: "",
				description: 'Job title',
				placeholder: 'Senior Developer',
				routing: { send: { type: 'body', property: 'title' } },
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		description: 'User ID',
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchUsers', searchable: true },
			},
			{
				displayName: 'By ID',
				name: 'id',
				type: 'string',
				placeholder: 'e.g. 12',
			},
			{
				displayName: 'By URL',
				name: 'url',
				type: 'string',
				placeholder: 'https://app.pachca.com/users/12345',
				extractValue: { type: 'regex', regex: 'https?://[^/]+/users/(\\d+)' },
				validation: [{ type: 'regex', properties: { regex: 'https?://[^/]+/users/(\\d+)', errorMessage: 'Not a valid Pachca user URL' } }],
			},
		],
		displayOptions: { show: { resource: ['user'], operation: ['delete'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userDeleteNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['delete'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['user'], operation: ['updateAvatar'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userUpdateAvatarNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['updateAvatar'] } },
	},
	{
		displayName: 'Input Binary Field',
		name: 'image',
		type: 'string',
		required: true,
		default: "data",
		description: 'Name of the binary property containing the avatar image. Use a previous node (e.g. HTTP Request, Read Binary File) to load the image.',
		displayOptions: { show: { resource: ['user'], operation: ['updateAvatar'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['user'], operation: ['deleteAvatar'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userDeleteAvatarNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['deleteAvatar'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['user'], operation: ['getStatus'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userGetStatusNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['getStatus'] } },
	},
	{
		displayName: 'Simplify',
		name: 'simplify',
		type: 'boolean',
		default: true,
		description: 'Whether to return a simplified version of the response instead of all fields',
		displayOptions: { show: { resource: ['user'], operation: ['getStatus'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['user'], operation: ['updateStatus'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userUpdateStatusNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['updateStatus'] } },
	},
	{
		displayName: 'Emoji',
		name: 'emoji',
		type: 'string',
		required: true,
		default: "",
		description: 'Status emoji character',
		displayOptions: { show: { resource: ['user'], operation: ['updateStatus'] } },
		placeholder: '🎮',
		routing: { send: { type: 'body', property: 'emoji' } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: "",
		description: 'Status text',
		displayOptions: { show: { resource: ['user'], operation: ['updateStatus'] } },
		placeholder: 'Very busy',
		routing: { send: { type: 'body', property: 'title' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['user'], operation: ['updateStatus'] } },
		options: [
			{
				displayName: 'Away Message',
				name: 'awayMessage',
				type: 'string',
				default: "",
				description: 'Away mode message text. Displayed in the profile and in direct messages/mentions.',
				placeholder: 'Back after 3 PM',
				routing: { send: { type: 'body', property: 'away_message' } },
			},
			{
				displayName: 'Expires At',
				name: 'expiresAt',
				type: 'dateTime',
				default: "",
				description: 'Status expiration date and time (ISO-8601, UTC+0) in YYYY-MM-DDThh:mm:ss.sssZ format',
				placeholder: '2024-04-08T10:00:00.000Z',
				routing: { send: { type: 'body', property: 'expires_at' } },
			},
			{
				displayName: 'Is Away',
				name: 'isAway',
				type: 'boolean',
				default: false,
				description: 'Whether to "Away" mode',
				routing: { send: { type: 'body', property: 'is_away' } },
			},
		],
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['user'], operation: ['deleteStatus'] } },
	},
	{
		displayName: 'Requires admin permissions',
		name: 'userDeleteStatusNotice',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['user'], operation: ['deleteStatus'] } },
	},
];