// Auto-generated by generate-client.ts — do not edit manually.
import Foundation
import OpenAPIRuntime
import OpenAPIURLSession

public final class PachcaClient: @unchecked Sendable {
    private let client: Client

    public init(_ token: String) throws {
        self.client = Client(
            serverURL: try Servers.Server1.url(),
            configuration: .init(dateTranscoder: .iso8601WithFractionalSeconds),
            transport: URLSessionTransport(),
            middlewares: [BearerTokenMiddleware(token: token)]
        )
    }

    public var bot: BotGroup { BotGroup(client: client) }
    public var chat: ChatGroup { ChatGroup(client: client) }
    public var chatMember: ChatMemberGroup { ChatMemberGroup(client: client) }
    public var chatMessage: ChatMessageGroup { ChatMessageGroup(client: client) }
    public var common: CommonGroup { CommonGroup(client: client) }
    public var directUpload: DirectUploadGroup { DirectUploadGroup(client: client) }
    public var export: ExportGroup { ExportGroup(client: client) }
    public var form: FormGroup { FormGroup(client: client) }
    public var groupTag: GroupTagGroup { GroupTagGroup(client: client) }
    public var linkPreview: LinkPreviewGroup { LinkPreviewGroup(client: client) }
    public var message: MessageGroup { MessageGroup(client: client) }
    public var oAuth: OAuthGroup { OAuthGroup(client: client) }
    public var profile: ProfileGroup { ProfileGroup(client: client) }
    public var reaction: ReactionGroup { ReactionGroup(client: client) }
    public var readMember: ReadMemberGroup { ReadMemberGroup(client: client) }
    public var search: SearchGroup { SearchGroup(client: client) }
    public var security: SecurityGroup { SecurityGroup(client: client) }
    public var task: TaskGroup { TaskGroup(client: client) }
    public var thread: ThreadGroup { ThreadGroup(client: client) }
    public var upload: UploadGroup { UploadGroup(client: client) }
    public var user: UserGroup { UserGroup(client: client) }
    public var userStatus: UserStatusGroup { UserStatusGroup(client: client) }

    /// Upload a file using params from `upload.getUploadParams()`.
    /// Handles multipart form construction and `${filename}` substitution.
    /// Returns the file key for use in message attachments.
    public func uploadFile(
        _ uploadParams: Components.Schemas.UploadParams,
        file: Data,
        filename: String
    ) async throws -> String {
        let key = uploadParams.key.replacingOccurrences(of: "${filename}", with: filename)
        let boundary = "Boundary-\(UUID().uuidString)"
        var body = Data()
        let fields: [(String, String)] = [
            ("Content-Disposition", uploadParams.Content_hyphen_Disposition),
            ("acl", uploadParams.acl),
            ("policy", uploadParams.policy),
            ("x-amz-credential", uploadParams.x_hyphen_amz_hyphen_credential),
            ("x-amz-algorithm", uploadParams.x_hyphen_amz_hyphen_algorithm),
            ("x-amz-date", uploadParams.x_hyphen_amz_hyphen_date),
            ("x-amz-signature", uploadParams.x_hyphen_amz_hyphen_signature),
            ("key", key),
        ]
        for (name, value) in fields {
            body.append("--\(boundary)\r\n".data(using: .utf8)!)
            body.append("Content-Disposition: form-data; name=\"\(name)\"\r\n\r\n".data(using: .utf8)!)
            body.append("\(value)\r\n".data(using: .utf8)!)
        }
        body.append("--\(boundary)\r\n".data(using: .utf8)!)
        body.append("Content-Disposition: form-data; name=\"file\"; filename=\"\(filename)\"\r\n".data(using: .utf8)!)
        body.append("Content-Type: application/octet-stream\r\n\r\n".data(using: .utf8)!)
        body.append(file)
        body.append("\r\n--\(boundary)--\r\n".data(using: .utf8)!)
        var request = URLRequest(url: URL(string: uploadParams.direct_url)!)
        request.httpMethod = "POST"
        request.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
        request.httpBody = body
        let (_, response) = try await URLSession.shared.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse, (httpResponse.statusCode == 201 || httpResponse.statusCode == 204) else {
            let code = (response as? HTTPURLResponse)?.statusCode ?? -1
            throw NSError(domain: "PachcaUpload", code: code, userInfo: [NSLocalizedDescriptionKey: "Upload failed with status \(code)"])
        }
        return key
    }
}
