// Auto-generated by generate-client.ts — do not edit manually.
import Foundation
import OpenAPIRuntime
import OpenAPIURLSession

public final class PachcaClient: @unchecked Sendable {
    private let client: Client

    public init(_ token: String) throws {
        self.client = Client(
            serverURL: try Servers.Server1.url(),
            configuration: .init(dateTranscoder: .iso8601WithFractionalSeconds),
            transport: URLSessionTransport(),
            middlewares: [BearerTokenMiddleware(token: token)]
        )
    }

    public var bot: BotGroup { BotGroup(client: client) }
    public var chat: ChatGroup { ChatGroup(client: client) }
    public var chatMember: ChatMemberGroup { ChatMemberGroup(client: client) }
    public var chatMessage: ChatMessageGroup { ChatMessageGroup(client: client) }
    public var common: CommonGroup { CommonGroup(client: client) }
    public var directUpload: DirectUploadGroup { DirectUploadGroup(client: client) }
    public var export: ExportGroup { ExportGroup(client: client) }
    public var form: FormGroup { FormGroup(client: client) }
    public var groupTag: GroupTagGroup { GroupTagGroup(client: client) }
    public var linkPreview: LinkPreviewGroup { LinkPreviewGroup(client: client) }
    public var message: MessageGroup { MessageGroup(client: client) }
    public var oAuth: OAuthGroup { OAuthGroup(client: client) }
    public var profile: ProfileGroup { ProfileGroup(client: client) }
    public var reaction: ReactionGroup { ReactionGroup(client: client) }
    public var readMember: ReadMemberGroup { ReadMemberGroup(client: client) }
    public var search: SearchGroup { SearchGroup(client: client) }
    public var security: SecurityGroup { SecurityGroup(client: client) }
    public var task: TaskGroup { TaskGroup(client: client) }
    public var thread: ThreadGroup { ThreadGroup(client: client) }
    public var upload: UploadGroup { UploadGroup(client: client) }
    public var user: UserGroup { UserGroup(client: client) }
    public var userStatus: UserStatusGroup { UserStatusGroup(client: client) }
}
