// Auto-generated by generate-client.ts — do not edit manually.

// MARK: - BotsGroup
public struct BotsGroup: Sendable {
    let client: Client

    public func updateBot(_ input: Operations.BotOperations_updateBot.Input) async throws -> Operations.BotOperations_updateBot.Output.Ok.Body.jsonPayload {
        try await client.BotOperations_updateBot(input).ok.body.json
    }

    public func getWebhookEvents(_ input: Operations.BotOperations_getWebhookEvents.Input) async throws -> Operations.BotOperations_getWebhookEvents.Output.Ok.Body.jsonPayload {
        try await client.BotOperations_getWebhookEvents(input).ok.body.json
    }

    public func deleteWebhookEvent(_ input: Operations.BotOperations_deleteWebhookEvent.Input) async throws {
        _ = try await client.BotOperations_deleteWebhookEvent(input).noContent
    }

}

// MARK: - ChatsGroup
public struct ChatsGroup: Sendable {
    let client: Client

    public func listChats(_ input: Operations.ChatOperations_listChats.Input) async throws -> Operations.ChatOperations_listChats.Output.Ok.Body.jsonPayload {
        try await client.ChatOperations_listChats(input).ok.body.json
    }

    public func createChat(_ input: Operations.ChatOperations_createChat.Input) async throws -> Operations.ChatOperations_createChat.Output.Created.Body.jsonPayload {
        try await client.ChatOperations_createChat(input).created.body.json
    }

    public func getChat(_ input: Operations.ChatOperations_getChat.Input) async throws -> Operations.ChatOperations_getChat.Output.Ok.Body.jsonPayload {
        try await client.ChatOperations_getChat(input).ok.body.json
    }

    public func updateChat(_ input: Operations.ChatOperations_updateChat.Input) async throws -> Operations.ChatOperations_updateChat.Output.Ok.Body.jsonPayload {
        try await client.ChatOperations_updateChat(input).ok.body.json
    }

    public func archiveChat(_ input: Operations.ChatOperations_archiveChat.Input) async throws {
        _ = try await client.ChatOperations_archiveChat(input).noContent
    }

    public func unarchiveChat(_ input: Operations.ChatOperations_unarchiveChat.Input) async throws {
        _ = try await client.ChatOperations_unarchiveChat(input).noContent
    }

}

// MARK: - CommonGroup
public struct CommonGroup: Sendable {
    let client: Client

    public func requestExport(_ input: Operations.ExportOperations_requestExport.Input) async throws {
        _ = try await client.ExportOperations_requestExport(input).noContent
    }

    public func downloadExport(_ input: Operations.ExportOperations_downloadExport.Input) async throws -> Operations.ExportOperations_downloadExport.Output {
        try await client.ExportOperations_downloadExport(input)
    }

    public func listProperties(_ input: Operations.CommonOperations_listProperties.Input) async throws -> Operations.CommonOperations_listProperties.Output.Ok.Body.jsonPayload {
        try await client.CommonOperations_listProperties(input).ok.body.json
    }

    public func uploadFile(_ input: Operations.DirectUploadOperations_uploadFile.Input) async throws {
        _ = try await client.DirectUploadOperations_uploadFile(input).created
    }

    public func getUploadParams(_ input: Operations.UploadOperations_getUploadParams.Input) async throws -> Components.Schemas.UploadParams {
        try await client.UploadOperations_getUploadParams(input).created.body.json
    }

}

// MARK: - GroupTagsGroup
public struct GroupTagsGroup: Sendable {
    let client: Client

    public func listTags(_ input: Operations.GroupTagOperations_listTags.Input) async throws -> Operations.GroupTagOperations_listTags.Output.Ok.Body.jsonPayload {
        try await client.GroupTagOperations_listTags(input).ok.body.json
    }

    public func createTag(_ input: Operations.GroupTagOperations_createTag.Input) async throws -> Operations.GroupTagOperations_createTag.Output.Created.Body.jsonPayload {
        try await client.GroupTagOperations_createTag(input).created.body.json
    }

    public func getTag(_ input: Operations.GroupTagOperations_getTag.Input) async throws -> Operations.GroupTagOperations_getTag.Output.Ok.Body.jsonPayload {
        try await client.GroupTagOperations_getTag(input).ok.body.json
    }

    public func updateTag(_ input: Operations.GroupTagOperations_updateTag.Input) async throws -> Operations.GroupTagOperations_updateTag.Output.Ok.Body.jsonPayload {
        try await client.GroupTagOperations_updateTag(input).ok.body.json
    }

    public func deleteTag(_ input: Operations.GroupTagOperations_deleteTag.Input) async throws {
        _ = try await client.GroupTagOperations_deleteTag(input).noContent
    }

    public func getTagUsers(_ input: Operations.GroupTagOperations_getTagUsers.Input) async throws -> Operations.GroupTagOperations_getTagUsers.Output.Ok.Body.jsonPayload {
        try await client.GroupTagOperations_getTagUsers(input).ok.body.json
    }

}

// MARK: - LinkPreviewsGroup
public struct LinkPreviewsGroup: Sendable {
    let client: Client

    public func createLinkPreviews(_ input: Operations.LinkPreviewOperations_createLinkPreviews.Input) async throws {
        _ = try await client.LinkPreviewOperations_createLinkPreviews(input).noContent
    }

}

// MARK: - MembersGroup
public struct MembersGroup: Sendable {
    let client: Client

    public func addTags(_ input: Operations.ChatMemberOperations_addTags.Input) async throws {
        _ = try await client.ChatMemberOperations_addTags(input).noContent
    }

    public func removeTag(_ input: Operations.ChatMemberOperations_removeTag.Input) async throws {
        _ = try await client.ChatMemberOperations_removeTag(input).noContent
    }

    public func leaveChat(_ input: Operations.ChatMemberOperations_leaveChat.Input) async throws {
        _ = try await client.ChatMemberOperations_leaveChat(input).noContent
    }

    public func listMembers(_ input: Operations.ChatMemberOperations_listMembers.Input) async throws -> Operations.ChatMemberOperations_listMembers.Output.Ok.Body.jsonPayload {
        try await client.ChatMemberOperations_listMembers(input).ok.body.json
    }

    public func addMembers(_ input: Operations.ChatMemberOperations_addMembers.Input) async throws {
        _ = try await client.ChatMemberOperations_addMembers(input).noContent
    }

    public func updateMemberRole(_ input: Operations.ChatMemberOperations_updateMemberRole.Input) async throws {
        _ = try await client.ChatMemberOperations_updateMemberRole(input).noContent
    }

    public func removeMember(_ input: Operations.ChatMemberOperations_removeMember.Input) async throws {
        _ = try await client.ChatMemberOperations_removeMember(input).noContent
    }

}

// MARK: - MessagesGroup
public struct MessagesGroup: Sendable {
    let client: Client

    public func listChatMessages(_ input: Operations.ChatMessageOperations_listChatMessages.Input) async throws -> Operations.ChatMessageOperations_listChatMessages.Output.Ok.Body.jsonPayload {
        try await client.ChatMessageOperations_listChatMessages(input).ok.body.json
    }

    public func createMessage(_ input: Operations.MessageOperations_createMessage.Input) async throws -> Operations.MessageOperations_createMessage.Output.Created.Body.jsonPayload {
        try await client.MessageOperations_createMessage(input).created.body.json
    }

    public func getMessage(_ input: Operations.MessageOperations_getMessage.Input) async throws -> Operations.MessageOperations_getMessage.Output.Ok.Body.jsonPayload {
        try await client.MessageOperations_getMessage(input).ok.body.json
    }

    public func updateMessage(_ input: Operations.MessageOperations_updateMessage.Input) async throws -> Operations.MessageOperations_updateMessage.Output.Ok.Body.jsonPayload {
        try await client.MessageOperations_updateMessage(input).ok.body.json
    }

    public func deleteMessage(_ input: Operations.MessageOperations_deleteMessage.Input) async throws {
        _ = try await client.MessageOperations_deleteMessage(input).noContent
    }

    public func pinMessage(_ input: Operations.MessageOperations_pinMessage.Input) async throws {
        _ = try await client.MessageOperations_pinMessage(input).created
    }

    public func unpinMessage(_ input: Operations.MessageOperations_unpinMessage.Input) async throws {
        _ = try await client.MessageOperations_unpinMessage(input).noContent
    }

}

// MARK: - ProfileGroup
public struct ProfileGroup: Sendable {
    let client: Client

    public func getTokenInfo(_ input: Operations.OAuthOperations_getTokenInfo.Input) async throws -> Operations.OAuthOperations_getTokenInfo.Output.Ok.Body.jsonPayload {
        try await client.OAuthOperations_getTokenInfo(input).ok.body.json
    }

    public func getProfile(_ input: Operations.ProfileOperations_getProfile.Input) async throws -> Operations.ProfileOperations_getProfile.Output.Ok.Body.jsonPayload {
        try await client.ProfileOperations_getProfile(input).ok.body.json
    }

    public func getStatus(_ input: Operations.ProfileOperations_getStatus.Input) async throws -> Operations.ProfileOperations_getStatus.Output.Ok.Body.jsonPayload {
        try await client.ProfileOperations_getStatus(input).ok.body.json
    }

    public func updateStatus(_ input: Operations.ProfileOperations_updateStatus.Input) async throws -> Operations.ProfileOperations_updateStatus.Output.Ok.Body.jsonPayload {
        try await client.ProfileOperations_updateStatus(input).ok.body.json
    }

    public func deleteStatus(_ input: Operations.ProfileOperations_deleteStatus.Input) async throws {
        _ = try await client.ProfileOperations_deleteStatus(input).noContent
    }

}

// MARK: - ReactionsGroup
public struct ReactionsGroup: Sendable {
    let client: Client

    public func listReactions(_ input: Operations.ReactionOperations_listReactions.Input) async throws -> Operations.ReactionOperations_listReactions.Output.Ok.Body.jsonPayload {
        try await client.ReactionOperations_listReactions(input).ok.body.json
    }

    public func addReaction(_ input: Operations.ReactionOperations_addReaction.Input) async throws -> Components.Schemas.Reaction {
        try await client.ReactionOperations_addReaction(input).created.body.json
    }

    public func removeReaction(_ input: Operations.ReactionOperations_removeReaction.Input) async throws {
        _ = try await client.ReactionOperations_removeReaction(input).noContent
    }

}

// MARK: - ReadMembersGroup
public struct ReadMembersGroup: Sendable {
    let client: Client

    public func listReadMembers(_ input: Operations.ReadMemberOperations_listReadMembers.Input) async throws -> Operations.ReadMemberOperations_listReadMembers.Output.Ok.Body.jsonPayload {
        try await client.ReadMemberOperations_listReadMembers(input).ok.body.json
    }

}

// MARK: - SearchGroup
public struct SearchGroup: Sendable {
    let client: Client

    public func searchChats(_ input: Operations.SearchOperations_searchChats.Input) async throws -> Operations.SearchOperations_searchChats.Output.Ok.Body.jsonPayload {
        try await client.SearchOperations_searchChats(input).ok.body.json
    }

    public func searchMessages(_ input: Operations.SearchOperations_searchMessages.Input) async throws -> Operations.SearchOperations_searchMessages.Output.Ok.Body.jsonPayload {
        try await client.SearchOperations_searchMessages(input).ok.body.json
    }

    public func searchUsers(_ input: Operations.SearchOperations_searchUsers.Input) async throws -> Operations.SearchOperations_searchUsers.Output.Ok.Body.jsonPayload {
        try await client.SearchOperations_searchUsers(input).ok.body.json
    }

}

// MARK: - SecurityGroup
public struct SecurityGroup: Sendable {
    let client: Client

    public func getAuditEvents(_ input: Operations.SecurityOperations_getAuditEvents.Input) async throws -> Operations.SecurityOperations_getAuditEvents.Output.Ok.Body.jsonPayload {
        try await client.SecurityOperations_getAuditEvents(input).ok.body.json
    }

}

// MARK: - TasksGroup
public struct TasksGroup: Sendable {
    let client: Client

    public func listTasks(_ input: Operations.TaskOperations_listTasks.Input) async throws -> Operations.TaskOperations_listTasks.Output.Ok.Body.jsonPayload {
        try await client.TaskOperations_listTasks(input).ok.body.json
    }

    public func createTask(_ input: Operations.TaskOperations_createTask.Input) async throws -> Operations.TaskOperations_createTask.Output.Created.Body.jsonPayload {
        try await client.TaskOperations_createTask(input).created.body.json
    }

    public func getTask(_ input: Operations.TaskOperations_getTask.Input) async throws -> Operations.TaskOperations_getTask.Output.Ok.Body.jsonPayload {
        try await client.TaskOperations_getTask(input).ok.body.json
    }

    public func updateTask(_ input: Operations.TaskOperations_updateTask.Input) async throws -> Operations.TaskOperations_updateTask.Output.Ok.Body.jsonPayload {
        try await client.TaskOperations_updateTask(input).ok.body.json
    }

    public func deleteTask(_ input: Operations.TaskOperations_deleteTask.Input) async throws {
        _ = try await client.TaskOperations_deleteTask(input).noContent
    }

}

// MARK: - ThreadsGroup
public struct ThreadsGroup: Sendable {
    let client: Client

    public func createThread(_ input: Operations.ThreadOperations_createThread.Input) async throws -> Operations.ThreadOperations_createThread.Output.Created.Body.jsonPayload {
        try await client.ThreadOperations_createThread(input).created.body.json
    }

    public func getThread(_ input: Operations.ThreadOperations_getThread.Input) async throws -> Operations.ThreadOperations_getThread.Output.Ok.Body.jsonPayload {
        try await client.ThreadOperations_getThread(input).ok.body.json
    }

}

// MARK: - UsersGroup
public struct UsersGroup: Sendable {
    let client: Client

    public func listUsers(_ input: Operations.UserOperations_listUsers.Input) async throws -> Operations.UserOperations_listUsers.Output.Ok.Body.jsonPayload {
        try await client.UserOperations_listUsers(input).ok.body.json
    }

    public func createUser(_ input: Operations.UserOperations_createUser.Input) async throws -> Operations.UserOperations_createUser.Output.Created.Body.jsonPayload {
        try await client.UserOperations_createUser(input).created.body.json
    }

    public func getUser(_ input: Operations.UserOperations_getUser.Input) async throws -> Operations.UserOperations_getUser.Output.Ok.Body.jsonPayload {
        try await client.UserOperations_getUser(input).ok.body.json
    }

    public func updateUser(_ input: Operations.UserOperations_updateUser.Input) async throws -> Operations.UserOperations_updateUser.Output.Ok.Body.jsonPayload {
        try await client.UserOperations_updateUser(input).ok.body.json
    }

    public func deleteUser(_ input: Operations.UserOperations_deleteUser.Input) async throws {
        _ = try await client.UserOperations_deleteUser(input).noContent
    }

    public func getUserStatus(_ input: Operations.UserStatusOperations_getUserStatus.Input) async throws -> Operations.UserStatusOperations_getUserStatus.Output.Ok.Body.jsonPayload {
        try await client.UserStatusOperations_getUserStatus(input).ok.body.json
    }

    public func updateUserStatus(_ input: Operations.UserStatusOperations_updateUserStatus.Input) async throws -> Operations.UserStatusOperations_updateUserStatus.Output.Ok.Body.jsonPayload {
        try await client.UserStatusOperations_updateUserStatus(input).ok.body.json
    }

    public func deleteUserStatus(_ input: Operations.UserStatusOperations_deleteUserStatus.Input) async throws {
        _ = try await client.UserStatusOperations_deleteUserStatus(input).noContent
    }

}

// MARK: - ViewsGroup
public struct ViewsGroup: Sendable {
    let client: Client

    public func openView(_ input: Operations.FormOperations_openView.Input) async throws {
        _ = try await client.FormOperations_openView(input).created
    }

}
