// AUTO-GENERATED by generate-client.ts — do not edit manually

import { createClient } from "./generated/client/index.js";
import type { Client, Options } from "./generated/client/index.js";
import {
  addMembers,
  addReaction,
  addTags,
  archiveChat,
  createChat,
  createLinkPreviews,
  createMessage,
  createTag,
  createTask,
  createThread,
  createUser,
  deleteMessage,
  deleteStatus,
  deleteTag,
  deleteTask,
  deleteUser,
  deleteUserStatus,
  deleteWebhookEvent,
  downloadExport,
  getAuditEvents,
  getChat,
  getMessage,
  getProfile,
  getStatus,
  getTag,
  getTagUsers,
  getTask,
  getThread,
  getTokenInfo,
  getUploadParams,
  getUser,
  getUserStatus,
  getWebhookEvents,
  leaveChat,
  listChatMessages,
  listChats,
  listMembers,
  listProperties,
  listReactions,
  listReadMembers,
  listTags,
  listTasks,
  listUsers,
  openView,
  pinMessage,
  removeMember,
  removeReaction,
  removeTag,
  requestExport,
  searchChats,
  searchMessages,
  searchUsers,
  unarchiveChat,
  unpinMessage,
  updateBot,
  updateChat,
  updateMemberRole,
  updateMessage,
  updateStatus,
  updateTag,
  updateTask,
  updateUser,
  updateUserStatus,
  uploadFile,
} from "./generated/sdk.gen.js";
import type {
  AddMembersData,
  AddReactionData,
  AddTagsData,
  ArchiveChatData,
  CreateChatData,
  CreateLinkPreviewsData,
  CreateMessageData,
  CreateTagData,
  CreateTaskData,
  CreateThreadData,
  CreateUserData,
  DeleteMessageData,
  DeleteStatusData,
  DeleteTagData,
  DeleteTaskData,
  DeleteUserData,
  DeleteUserStatusData,
  DeleteWebhookEventData,
  DownloadExportData,
  GetAuditEventsData,
  GetChatData,
  GetMessageData,
  GetProfileData,
  GetStatusData,
  GetTagData,
  GetTagUsersData,
  GetTaskData,
  GetThreadData,
  GetTokenInfoData,
  GetUploadParamsData,
  GetUserData,
  GetUserStatusData,
  GetWebhookEventsData,
  LeaveChatData,
  ListChatMessagesData,
  ListChatsData,
  ListMembersData,
  ListPropertiesData,
  ListReactionsData,
  ListReadMembersData,
  ListTagsData,
  ListTasksData,
  ListUsersData,
  OpenViewData,
  PinMessageData,
  RemoveMemberData,
  RemoveReactionData,
  RemoveTagData,
  RequestExportData,
  SearchChatsData,
  SearchMessagesData,
  SearchUsersData,
  UnarchiveChatData,
  UnpinMessageData,
  UpdateBotData,
  UpdateChatData,
  UpdateMemberRoleData,
  UpdateMessageData,
  UpdateStatusData,
  UpdateTagData,
  UpdateTaskData,
  UpdateUserData,
  UpdateUserStatusData,
  UploadFileData,
  UploadParams,
} from "./generated/types.gen.js";
import { paginate } from "./paginate.js";

export interface PachcaConfig {
  /** Bearer access token */
  token: string;
  /** Base URL (default: https://api.pachca.com/api/shared/v1) */
  baseUrl?: string;
}

export class Pachca {
  private readonly client: Client;

  constructor(config: PachcaConfig) {
    this.client = createClient({
      baseUrl: config.baseUrl ?? "https://api.pachca.com/api/shared/v1",
      auth: () => config.token,
    });
  }

  // ── messages ──────────────────────────────────────────

  readonly messages = {
    listChatMessages: (options: Omit<Options<ListChatMessagesData>, "client">) =>
      listChatMessages({ ...options, client: this.client } as Options<ListChatMessagesData>),
    createMessage: (options: Omit<Options<CreateMessageData>, "client">) =>
      createMessage({ ...options, client: this.client } as Options<CreateMessageData>),
    deleteMessage: (options: Omit<Options<DeleteMessageData>, "client">) =>
      deleteMessage({ ...options, client: this.client } as Options<DeleteMessageData>),
    getMessage: (options: Omit<Options<GetMessageData>, "client">) =>
      getMessage({ ...options, client: this.client } as Options<GetMessageData>),
    updateMessage: (options: Omit<Options<UpdateMessageData>, "client">) =>
      updateMessage({ ...options, client: this.client } as Options<UpdateMessageData>),
    unpinMessage: (options: Omit<Options<UnpinMessageData>, "client">) =>
      unpinMessage({ ...options, client: this.client } as Options<UnpinMessageData>),
    pinMessage: (options: Omit<Options<PinMessageData>, "client">) =>
      pinMessage({ ...options, client: this.client } as Options<PinMessageData>),
    listAllChatMessages: (options: Omit<Options<ListChatMessagesData>, "client">) =>
      paginate(
        (opts: any) => listChatMessages({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── chats ─────────────────────────────────────────────

  readonly chats = {
    listChats: (options?: Omit<Options<ListChatsData>, "client">) =>
      listChats({ ...options, client: this.client } as Options<ListChatsData>),
    createChat: (options: Omit<Options<CreateChatData>, "client">) =>
      createChat({ ...options, client: this.client } as Options<CreateChatData>),
    getChat: (options: Omit<Options<GetChatData>, "client">) =>
      getChat({ ...options, client: this.client } as Options<GetChatData>),
    updateChat: (options: Omit<Options<UpdateChatData>, "client">) =>
      updateChat({ ...options, client: this.client } as Options<UpdateChatData>),
    archiveChat: (options: Omit<Options<ArchiveChatData>, "client">) =>
      archiveChat({ ...options, client: this.client } as Options<ArchiveChatData>),
    unarchiveChat: (options: Omit<Options<UnarchiveChatData>, "client">) =>
      unarchiveChat({ ...options, client: this.client } as Options<UnarchiveChatData>),
    listAllChats: (options?: Omit<Options<ListChatsData>, "client">) =>
      paginate(
        (opts: any) => listChats({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── users ─────────────────────────────────────────────

  readonly users = {
    listUsers: (options?: Omit<Options<ListUsersData>, "client">) =>
      listUsers({ ...options, client: this.client } as Options<ListUsersData>),
    createUser: (options: Omit<Options<CreateUserData>, "client">) =>
      createUser({ ...options, client: this.client } as Options<CreateUserData>),
    deleteUser: (options: Omit<Options<DeleteUserData>, "client">) =>
      deleteUser({ ...options, client: this.client } as Options<DeleteUserData>),
    getUser: (options: Omit<Options<GetUserData>, "client">) =>
      getUser({ ...options, client: this.client } as Options<GetUserData>),
    updateUser: (options: Omit<Options<UpdateUserData>, "client">) =>
      updateUser({ ...options, client: this.client } as Options<UpdateUserData>),
    deleteUserStatus: (options: Omit<Options<DeleteUserStatusData>, "client">) =>
      deleteUserStatus({ ...options, client: this.client } as Options<DeleteUserStatusData>),
    getUserStatus: (options: Omit<Options<GetUserStatusData>, "client">) =>
      getUserStatus({ ...options, client: this.client } as Options<GetUserStatusData>),
    updateUserStatus: (options: Omit<Options<UpdateUserStatusData>, "client">) =>
      updateUserStatus({ ...options, client: this.client } as Options<UpdateUserStatusData>),
    listAllUsers: (options?: Omit<Options<ListUsersData>, "client">) =>
      paginate(
        (opts: any) => listUsers({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── tasks ─────────────────────────────────────────────

  readonly tasks = {
    listTasks: (options?: Omit<Options<ListTasksData>, "client">) =>
      listTasks({ ...options, client: this.client } as Options<ListTasksData>),
    createTask: (options: Omit<Options<CreateTaskData>, "client">) =>
      createTask({ ...options, client: this.client } as Options<CreateTaskData>),
    deleteTask: (options: Omit<Options<DeleteTaskData>, "client">) =>
      deleteTask({ ...options, client: this.client } as Options<DeleteTaskData>),
    getTask: (options: Omit<Options<GetTaskData>, "client">) =>
      getTask({ ...options, client: this.client } as Options<GetTaskData>),
    updateTask: (options: Omit<Options<UpdateTaskData>, "client">) =>
      updateTask({ ...options, client: this.client } as Options<UpdateTaskData>),
    listAllTasks: (options?: Omit<Options<ListTasksData>, "client">) =>
      paginate(
        (opts: any) => listTasks({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── tags ──────────────────────────────────────────────

  readonly tags = {
    listTags: (options?: Omit<Options<ListTagsData>, "client">) =>
      listTags({ ...options, client: this.client } as Options<ListTagsData>),
    createTag: (options: Omit<Options<CreateTagData>, "client">) =>
      createTag({ ...options, client: this.client } as Options<CreateTagData>),
    deleteTag: (options: Omit<Options<DeleteTagData>, "client">) =>
      deleteTag({ ...options, client: this.client } as Options<DeleteTagData>),
    getTag: (options: Omit<Options<GetTagData>, "client">) =>
      getTag({ ...options, client: this.client } as Options<GetTagData>),
    updateTag: (options: Omit<Options<UpdateTagData>, "client">) =>
      updateTag({ ...options, client: this.client } as Options<UpdateTagData>),
    getTagUsers: (options: Omit<Options<GetTagUsersData>, "client">) =>
      getTagUsers({ ...options, client: this.client } as Options<GetTagUsersData>),
    listAllTags: (options?: Omit<Options<ListTagsData>, "client">) =>
      paginate(
        (opts: any) => listTags({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
    getAllTagUsers: (options: Omit<Options<GetTagUsersData>, "client">) =>
      paginate(
        (opts: any) => getTagUsers({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── members ───────────────────────────────────────────

  readonly members = {
    addTags: (options: Omit<Options<AddTagsData>, "client">) =>
      addTags({ ...options, client: this.client } as Options<AddTagsData>),
    removeTag: (options: Omit<Options<RemoveTagData>, "client">) =>
      removeTag({ ...options, client: this.client } as Options<RemoveTagData>),
    leaveChat: (options: Omit<Options<LeaveChatData>, "client">) =>
      leaveChat({ ...options, client: this.client } as Options<LeaveChatData>),
    listMembers: (options: Omit<Options<ListMembersData>, "client">) =>
      listMembers({ ...options, client: this.client } as Options<ListMembersData>),
    addMembers: (options: Omit<Options<AddMembersData>, "client">) =>
      addMembers({ ...options, client: this.client } as Options<AddMembersData>),
    removeMember: (options: Omit<Options<RemoveMemberData>, "client">) =>
      removeMember({ ...options, client: this.client } as Options<RemoveMemberData>),
    updateMemberRole: (options: Omit<Options<UpdateMemberRoleData>, "client">) =>
      updateMemberRole({ ...options, client: this.client } as Options<UpdateMemberRoleData>),
    listAllMembers: (options: Omit<Options<ListMembersData>, "client">) =>
      paginate(
        (opts: any) => listMembers({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── reactions ─────────────────────────────────────────

  readonly reactions = {
    removeReaction: (options: Omit<Options<RemoveReactionData>, "client">) =>
      removeReaction({ ...options, client: this.client } as Options<RemoveReactionData>),
    listReactions: (options: Omit<Options<ListReactionsData>, "client">) =>
      listReactions({ ...options, client: this.client } as Options<ListReactionsData>),
    addReaction: (options: Omit<Options<AddReactionData>, "client">) =>
      addReaction({ ...options, client: this.client } as Options<AddReactionData>),
    listAllReactions: (options: Omit<Options<ListReactionsData>, "client">) =>
      paginate(
        (opts: any) => listReactions({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── profile ───────────────────────────────────────────

  readonly profile = {
    getTokenInfo: (options?: Omit<Options<GetTokenInfoData>, "client">) =>
      getTokenInfo({ ...options, client: this.client } as Options<GetTokenInfoData>),
    getProfile: (options?: Omit<Options<GetProfileData>, "client">) =>
      getProfile({ ...options, client: this.client } as Options<GetProfileData>),
    deleteStatus: (options?: Omit<Options<DeleteStatusData>, "client">) =>
      deleteStatus({ ...options, client: this.client } as Options<DeleteStatusData>),
    getStatus: (options?: Omit<Options<GetStatusData>, "client">) =>
      getStatus({ ...options, client: this.client } as Options<GetStatusData>),
    updateStatus: (options: Omit<Options<UpdateStatusData>, "client">) =>
      updateStatus({ ...options, client: this.client } as Options<UpdateStatusData>),
  };

  // ── bots ──────────────────────────────────────────────

  readonly bots = {
    updateBot: (options: Omit<Options<UpdateBotData>, "client">) =>
      updateBot({ ...options, client: this.client } as Options<UpdateBotData>),
    getWebhookEvents: (options?: Omit<Options<GetWebhookEventsData>, "client">) =>
      getWebhookEvents({ ...options, client: this.client } as Options<GetWebhookEventsData>),
    deleteWebhookEvent: (options: Omit<Options<DeleteWebhookEventData>, "client">) =>
      deleteWebhookEvent({ ...options, client: this.client } as Options<DeleteWebhookEventData>),
    getAllWebhookEvents: (options?: Omit<Options<GetWebhookEventsData>, "client">) =>
      paginate(
        (opts: any) => getWebhookEvents({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── security ──────────────────────────────────────────

  readonly security = {
    getAuditEvents: (options: Omit<Options<GetAuditEventsData>, "client">) =>
      getAuditEvents({ ...options, client: this.client } as Options<GetAuditEventsData>),
    getAllAuditEvents: (options: Omit<Options<GetAuditEventsData>, "client">) =>
      paginate(
        (opts: any) => getAuditEvents({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── common ────────────────────────────────────────────

  readonly common = {
    requestExport: (options: Omit<Options<RequestExportData>, "client">) =>
      requestExport({ ...options, client: this.client } as Options<RequestExportData>),
    downloadExport: (options: Omit<Options<DownloadExportData>, "client">) =>
      downloadExport({ ...options, client: this.client } as Options<DownloadExportData>),
    listProperties: (options: Omit<Options<ListPropertiesData>, "client">) =>
      listProperties({ ...options, client: this.client } as Options<ListPropertiesData>),
    uploadFile: (options: Omit<Options<UploadFileData>, "client">) =>
      uploadFile({ ...options, client: this.client } as Options<UploadFileData>),
    createLinkPreviews: (options: Omit<Options<CreateLinkPreviewsData>, "client">) =>
      createLinkPreviews({ ...options, client: this.client } as Options<CreateLinkPreviewsData>),
    listReadMembers: (options: Omit<Options<ListReadMembersData>, "client">) =>
      listReadMembers({ ...options, client: this.client } as Options<ListReadMembersData>),
    createThread: (options: Omit<Options<CreateThreadData>, "client">) =>
      createThread({ ...options, client: this.client } as Options<CreateThreadData>),
    searchChats: (options?: Omit<Options<SearchChatsData>, "client">) =>
      searchChats({ ...options, client: this.client } as Options<SearchChatsData>),
    searchMessages: (options?: Omit<Options<SearchMessagesData>, "client">) =>
      searchMessages({ ...options, client: this.client } as Options<SearchMessagesData>),
    searchUsers: (options?: Omit<Options<SearchUsersData>, "client">) =>
      searchUsers({ ...options, client: this.client } as Options<SearchUsersData>),
    getThread: (options: Omit<Options<GetThreadData>, "client">) =>
      getThread({ ...options, client: this.client } as Options<GetThreadData>),
    getUploadParams: (options?: Omit<Options<GetUploadParamsData>, "client">) =>
      getUploadParams({ ...options, client: this.client } as Options<GetUploadParamsData>),
    openView: (options: Omit<Options<OpenViewData>, "client">) =>
      openView({ ...options, client: this.client } as Options<OpenViewData>),
    listAllReadMembers: (options: Omit<Options<ListReadMembersData>, "client">) =>
      paginate(
        (opts: any) => listReadMembers({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
    searchAllChats: (options?: Omit<Options<SearchChatsData>, "client">) =>
      paginate(
        (opts: any) => searchChats({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
    searchAllMessages: (options?: Omit<Options<SearchMessagesData>, "client">) =>
      paginate(
        (opts: any) => searchMessages({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
    searchAllUsers: (options?: Omit<Options<SearchUsersData>, "client">) =>
      paginate(
        (opts: any) => searchUsers({ ...opts, client: this.client }),
        (options ?? {}) as any,
      ),
  };

  // ── uploads ──────────────────────────────────────────

  /**
   * Upload a file using params from common.getUploadParams().
   * Handles multipart form construction and ${filename} substitution.
   * Returns the file key for use in message attachments.
   */
  async uploadFile(
    uploadParams: UploadParams,
    file: Blob,
    filename: string,
  ): Promise<string> {
    const key = uploadParams.key.replace("${filename}", filename);
    const form = new FormData();
    form.append("Content-Disposition", uploadParams["Content-Disposition"]);
    form.append("acl", uploadParams.acl);
    form.append("policy", uploadParams.policy);
    form.append("x-amz-credential", uploadParams["x-amz-credential"]);
    form.append("x-amz-algorithm", uploadParams["x-amz-algorithm"]);
    form.append("x-amz-date", uploadParams["x-amz-date"]);
    form.append("x-amz-signature", uploadParams["x-amz-signature"]);
    form.append("key", key);
    form.append("file", file, filename);
    const resp = await fetch(uploadParams.direct_url, {
      method: "POST",
      body: form,
    });
    if (resp.status !== 201 && resp.status !== 204) {
      throw new Error(`Upload failed with status ${resp.status}`);
    }
    return key;
  }
}
